# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Scipp contributors (https://github.com/scipp)
"""Auto-generated NeXus f144 stream declarations.

Do not edit by hand. Regenerate with
``python -m ess.livedata.nexus_helpers <geometry.nxs> --generate``.

Source: coda_loki_999999_00002438.hdf
"""

from ess.livedata.config import F144Stream

PARSED_STREAMS: dict[str, F144Stream] = {
    '/entry/instrument/beam_monitor_m2/monitor_positioner/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m2/monitor_positioner/idle_flag',
        source='LOKI-InBmM2:MC-LinZ-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beam_monitor_m2/monitor_positioner/target_value': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m2/monitor_positioner/target_value',
        source='LOKI-InBmM2:MC-LinZ-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beam_monitor_m2/monitor_positioner/value': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m2/monitor_positioner/value',
        source='LOKI-InBmM2:MC-LinZ-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beam_monitor_m3/monitor_positioner/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m3/monitor_positioner/idle_flag',
        source='LOKI-InBmM3:MC-LinZ-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beam_monitor_m3/monitor_positioner/target_value': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m3/monitor_positioner/target_value',
        source='LOKI-InBmM3:MC-LinZ-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beam_monitor_m3/monitor_positioner/value': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m3/monitor_positioner/value',
        source='LOKI-InBmM3:MC-LinZ-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beam_monitor_m4/monitor_positioner/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m4/monitor_positioner/idle_flag',
        source='LOKI-DtBS1:MC-LinZ-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beam_monitor_m4/monitor_positioner/target_value': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m4/monitor_positioner/target_value',
        source='LOKI-DtBS1:MC-LinZ-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beam_monitor_m4/monitor_positioner/value': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m4/monitor_positioner/value',
        source='LOKI-DtBS1:MC-LinZ-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beam_monitor_m4/transformations/trans_20': F144Stream(
        nexus_path='/entry/instrument/beam_monitor_m4/transformations/trans_20',
        source='source',
        topic='loki_motion',
        units='m',
    ),
    '/entry/instrument/beamstop_x/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beamstop_x/idle_flag',
        source='LOKI-DtBS1:MC-LinX-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beamstop_x/target_value': F144Stream(
        nexus_path='/entry/instrument/beamstop_x/target_value',
        source='LOKI-DtBS1:MC-LinX-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_x/value': F144Stream(
        nexus_path='/entry/instrument/beamstop_x/value',
        source='LOKI-DtBS1:MC-LinX-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_y/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beamstop_y/idle_flag',
        source='LOKI-DtBS1:MC-LinY-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beamstop_y/target_value': F144Stream(
        nexus_path='/entry/instrument/beamstop_y/target_value',
        source='LOKI-DtBS1:MC-LinY-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_y/value': F144Stream(
        nexus_path='/entry/instrument/beamstop_y/value',
        source='LOKI-DtBS1:MC-LinY-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z1/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beamstop_z1/idle_flag',
        source='LOKI-DtBS1:MC-LinZ-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beamstop_z1/target_value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z1/target_value',
        source='LOKI-DtBS1:MC-LinZ-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z1/value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z1/value',
        source='LOKI-DtBS1:MC-LinZ-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z2/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beamstop_z2/idle_flag',
        source='LOKI-DtBS1:MC-LinZ-02:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beamstop_z2/target_value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z2/target_value',
        source='LOKI-DtBS1:MC-LinZ-02:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z2/value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z2/value',
        source='LOKI-DtBS1:MC-LinZ-02:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z3/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beamstop_z3/idle_flag',
        source='LOKI-DtBS1:MC-LinZ-03:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beamstop_z3/target_value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z3/target_value',
        source='LOKI-DtBS1:MC-LinZ-03:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z3/value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z3/value',
        source='LOKI-DtBS1:MC-LinZ-03:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z4/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beamstop_z4/idle_flag',
        source='LOKI-DtBS1:MC-LinZ-04:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beamstop_z4/target_value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z4/target_value',
        source='LOKI-DtBS1:MC-LinZ-04:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z4/value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z4/value',
        source='LOKI-DtBS1:MC-LinZ-04:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z5/idle_flag': F144Stream(
        nexus_path='/entry/instrument/beamstop_z5/idle_flag',
        source='LOKI-DtBS1:MC-LinZ-05:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/beamstop_z5/target_value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z5/target_value',
        source='LOKI-DtBS1:MC-LinZ-05:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/beamstop_z5/value': F144Stream(
        nexus_path='/entry/instrument/beamstop_z5/value',
        source='LOKI-DtBS1:MC-LinZ-05:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/bw_chopper1/delay': F144Stream(
        nexus_path='/entry/instrument/bw_chopper1/delay',
        source='LOKI-ChpSy1:Chop-BWC-101:TotDly',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/bw_chopper1/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/bw_chopper1/experiment_delay',
        source='LOKI-ChpSy1:Chop-BWC-101:ChopDly-S',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/bw_chopper1/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/bw_chopper1/pulse_delay',
        source='LOKI-ChpSy1:Chop-BWC-101:BeamPosDly-S',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/bw_chopper1/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/bw_chopper1/rotation_speed',
        source='LOKI-ChpSy1:Chop-BWC-101:Spd_R',
        topic='loki_choppers',
        units='Hz',
    ),
    '/entry/instrument/bw_chopper1/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/bw_chopper1/rotation_speed_setpoint',
        source='LOKI-ChpSy1:Chop-BWC-101:Spd_S',
        topic='loki_choppers',
        units='Hz',
    ),
    '/entry/instrument/bw_chopper2/delay': F144Stream(
        nexus_path='/entry/instrument/bw_chopper2/delay',
        source='LOKI-ChpSy1:Chop-BWC-102:TotDly',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/bw_chopper2/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/bw_chopper2/experiment_delay',
        source='LOKI-ChpSy1:Chop-BWC-102:ChopDly-S',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/bw_chopper2/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/bw_chopper2/pulse_delay',
        source='LOKI-ChpSy1:Chop-BWC-102:BeamPosDly-S',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/bw_chopper2/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/bw_chopper2/rotation_speed',
        source='LOKI-ChpSy1:Chop-BWC-102:Spd_R',
        topic='loki_choppers',
        units='Hz',
    ),
    '/entry/instrument/bw_chopper2/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/bw_chopper2/rotation_speed_setpoint',
        source='LOKI-ChpSy1:Chop-BWC-102:Spd_S',
        topic='loki_choppers',
        units='Hz',
    ),
    '/entry/instrument/collimator_selector_1/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimator_selector_1/idle_flag',
        source='LOKI-ColCh1:MC-LinY-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimator_selector_1/target_value': F144Stream(
        nexus_path='/entry/instrument/collimator_selector_1/target_value',
        source='LOKI-ColCh1:MC-LinY-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/collimator_selector_1/value': F144Stream(
        nexus_path='/entry/instrument/collimator_selector_1/value',
        source='LOKI-ColCh1:MC-LinY-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/collimator_selector_2/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimator_selector_2/idle_flag',
        source='LOKI-ColCh2:MC-LinY-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimator_selector_2/target_value': F144Stream(
        nexus_path='/entry/instrument/collimator_selector_2/target_value',
        source='LOKI-ColCh2:MC-LinY-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/collimator_selector_2/value': F144Stream(
        nexus_path='/entry/instrument/collimator_selector_2/value',
        source='LOKI-ColCh2:MC-LinY-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/detector_carriage/idle_flag': F144Stream(
        nexus_path='/entry/instrument/detector_carriage/idle_flag',
        source='LOKI-DtCar1:MC-LinX-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/detector_carriage/target_value': F144Stream(
        nexus_path='/entry/instrument/detector_carriage/target_value',
        source='LOKI-DtCar1:MC-LinX-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/detector_carriage/value': F144Stream(
        nexus_path='/entry/instrument/detector_carriage/value',
        source='LOKI-DtCar1:MC-LinX-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/experiment_shutter/value': F144Stream(
        nexus_path='/entry/instrument/experiment_shutter/value',
        source='LOKI-ExSh:MC-Pne-01:ShtAuxBits07',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/fo_chopper1/delay': F144Stream(
        nexus_path='/entry/instrument/fo_chopper1/delay',
        source='LOKI-ChpSy3:Chop-SFOC-101:TotDly',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/fo_chopper1/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/fo_chopper1/experiment_delay',
        source='LOKI-ChpSy3:Chop-SFOC-101:ChopDly-S',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/fo_chopper1/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/fo_chopper1/pulse_delay',
        source='LOKI-ChpSy3:Chop-SFOC-101:BeamPosDly-S',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/fo_chopper1/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/fo_chopper1/rotation_speed',
        source='LOKI-ChpSy3:Chop-SFOC-101:Spd_R',
        topic='loki_choppers',
        units='Hz',
    ),
    '/entry/instrument/fo_chopper1/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/fo_chopper1/rotation_speed_setpoint',
        source='LOKI-ChpSy3:Chop-SFOC-101:Spd_S',
        topic='loki_choppers',
        units='Hz',
    ),
    '/entry/instrument/fo_chopper2/delay': F144Stream(
        nexus_path='/entry/instrument/fo_chopper2/delay',
        source='LOKI-ChpSy3:Chop-SFOC-102:TotDly',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/fo_chopper2/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/fo_chopper2/experiment_delay',
        source='LOKI-ChpSy3:Chop-SFOC-102:ChopDly-S',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/fo_chopper2/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/fo_chopper2/pulse_delay',
        source='LOKI-ChpSy3:Chop-SFOC-102:BeamPosDly-S',
        topic='loki_choppers',
        units='ns',
    ),
    '/entry/instrument/fo_chopper2/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/fo_chopper2/rotation_speed',
        source='LOKI-ChpSy3:Chop-SFOC-102:Spd_R',
        topic='loki_choppers',
        units='Hz',
    ),
    '/entry/instrument/fo_chopper2/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/fo_chopper2/rotation_speed_setpoint',
        source='LOKI-ChpSy3:Chop-SFOC-102:Spd_S',
        topic='loki_choppers',
        units='Hz',
    ),
    '/entry/instrument/heavy_shutter/value': F144Stream(
        nexus_path='/entry/instrument/heavy_shutter/value',
        source='LOKI-HvSht:MC-Pne-01:ShtAuxBits07',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/laser_mirror/idle_flag': F144Stream(
        nexus_path='/entry/instrument/laser_mirror/idle_flag',
        source='LOKI-InBmLM:MC-LinZ-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/laser_mirror/target_value': F144Stream(
        nexus_path='/entry/instrument/laser_mirror/target_value',
        source='LOKI-InBmLM:MC-LinZ-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/laser_mirror/value': F144Stream(
        nexus_path='/entry/instrument/laser_mirror/value',
        source='LOKI-InBmLM:MC-LinZ-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/linear_sample_changer/idle_flag': F144Stream(
        nexus_path='/entry/instrument/linear_sample_changer/idle_flag',
        source='LOKI-SpChg1:MC-LinY-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/linear_sample_changer/target_value': F144Stream(
        nexus_path='/entry/instrument/linear_sample_changer/target_value',
        source='LOKI-SpChg1:MC-LinY-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/linear_sample_changer/value': F144Stream(
        nexus_path='/entry/instrument/linear_sample_changer/value',
        source='LOKI-SpChg1:MC-LinY-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/sample_position_z/value': F144Stream(
        nexus_path='/entry/instrument/sample_position_z/value',
        source='measured_sample_position_z',
        topic='loki_nicos_devices',
        units='m',
    ),
    '/entry/instrument/sample_rotation/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_rotation/idle_flag',
        source='LOKI-SpCel1:MC-RotX-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_rotation/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_rotation/target_value',
        source='LOKI-SpCel1:MC-RotX-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/sample_rotation/value': F144Stream(
        nexus_path='/entry/instrument/sample_rotation/value',
        source='LOKI-SpCel1:MC-RotX-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stack_x/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stack_x/idle_flag',
        source='LOKI-SpSt1:MC-LinX-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stack_x/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stack_x/target_value',
        source='LOKI-SpSt1:MC-LinX-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stack_x/value': F144Stream(
        nexus_path='/entry/instrument/sample_stack_x/value',
        source='LOKI-SpSt1:MC-LinX-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stack_y/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stack_y/idle_flag',
        source='LOKI-SpSt1:MC-LinY-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stack_y/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stack_y/target_value',
        source='LOKI-SpSt1:MC-LinY-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stack_y/value': F144Stream(
        nexus_path='/entry/instrument/sample_stack_y/value',
        source='LOKI-SpSt1:MC-LinY-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stack_z/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stack_z/idle_flag',
        source='LOKI-SpSt1:MC-LinZ-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stack_z/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stack_z/target_value',
        source='LOKI-SpSt1:MC-LinZ-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stack_z/value': F144Stream(
        nexus_path='/entry/instrument/sample_stack_z/value',
        source='LOKI-SpSt1:MC-LinZ-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_bottom/idle_flag',
        source='LOKI-ColSl1:MC-SlZm-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_bottom/target_value',
        source='LOKI-ColSl1:MC-SlZm-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_bottom/value',
        source='LOKI-ColSl1:MC-SlZm-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_left/idle_flag',
        source='LOKI-ColSl1:MC-SlYp-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_left/target_value',
        source='LOKI-ColSl1:MC-SlYp-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_left/value',
        source='LOKI-ColSl1:MC-SlYp-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_right/idle_flag',
        source='LOKI-ColSl1:MC-SlYm-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_right/target_value',
        source='LOKI-ColSl1:MC-SlYm-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_right/value',
        source='LOKI-ColSl1:MC-SlYm-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_top/idle_flag',
        source='LOKI-ColSl1:MC-SlZp-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_top/target_value',
        source='LOKI-ColSl1:MC-SlZp-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_top/value',
        source='LOKI-ColSl1:MC-SlZp-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_bottom/idle_flag',
        source='LOKI-ColSl2:MC-SlZm-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_bottom/target_value',
        source='LOKI-ColSl2:MC-SlZm-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_bottom/value',
        source='LOKI-ColSl2:MC-SlZm-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_left/idle_flag',
        source='LOKI-ColSl2:MC-SlYp-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_left/target_value',
        source='LOKI-ColSl2:MC-SlYp-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_left/value',
        source='LOKI-ColSl2:MC-SlYp-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_right/idle_flag',
        source='LOKI-ColSl2:MC-SlYm-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_right/target_value',
        source='LOKI-ColSl2:MC-SlYm-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_right/value',
        source='LOKI-ColSl2:MC-SlYm-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_top/idle_flag',
        source='LOKI-ColSl2:MC-SlZp-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_top/target_value',
        source='LOKI-ColSl2:MC-SlZp-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_top/value',
        source='LOKI-ColSl2:MC-SlZp-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_bottom/idle_flag',
        source='LOKI-ColSl3:MC-SlZm-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_3/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_bottom/target_value',
        source='LOKI-ColSl3:MC-SlZm-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_bottom/value',
        source='LOKI-ColSl3:MC-SlZm-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_left/idle_flag',
        source='LOKI-ColSl3:MC-SlYp-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_3/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_left/target_value',
        source='LOKI-ColSl3:MC-SlYp-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_left/value',
        source='LOKI-ColSl3:MC-SlYp-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_right/idle_flag',
        source='LOKI-ColSl3:MC-SlYm-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_3/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_right/target_value',
        source='LOKI-ColSl3:MC-SlYm-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_right/value',
        source='LOKI-ColSl3:MC-SlYm-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_top/idle_flag',
        source='LOKI-ColSl3:MC-SlZp-01:Mtr.DMOV',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_3/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_top/target_value',
        source='LOKI-ColSl3:MC-SlZp-01:Mtr.VAL',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_top/value',
        source='LOKI-ColSl3:MC-SlZp-01:Mtr.RBV',
        topic='loki_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_4/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_4/blade_bottom/value',
        source='measured_slit_set_4_bottom_blade',
        topic='loki_nicos_devices',
        units='m',
    ),
    '/entry/instrument/slit_set_4/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_4/blade_left/value',
        source='measured_slit_set_4_left_blade',
        topic='loki_nicos_devices',
        units='m',
    ),
    '/entry/instrument/slit_set_4/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_4/blade_right/value',
        source='measured_slit_set_4_right_blade',
        topic='loki_nicos_devices',
        units='m',
    ),
    '/entry/instrument/slit_set_4/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_4/blade_top/value',
        source='measured_slit_set_4_top_blade',
        topic='loki_nicos_devices',
        units='m',
    ),
    '/entry/instrument/slit_set_4/z_distance': F144Stream(
        nexus_path='/entry/instrument/slit_set_4/z_distance',
        source='measured_slit_set_4_z',
        topic='loki_nicos_devices',
        units='m',
    ),
    '/entry/instrument/thermometer_box_ts1/value': F144Stream(
        nexus_path='/entry/instrument/thermometer_box_ts1/value',
        source='LOKI-SE:Proc-TIC-001:PT100_TS1',
        topic='loki_misc_devices',
        units='C',
    ),
    '/entry/instrument/thermometer_box_ts2/value': F144Stream(
        nexus_path='/entry/instrument/thermometer_box_ts2/value',
        source='LOKI-SE:Proc-TIC-001:PT100_TS2',
        topic='loki_misc_devices',
        units='C',
    ),
    '/entry/instrument/thermometer_box_ts3/value': F144Stream(
        nexus_path='/entry/instrument/thermometer_box_ts3/value',
        source='LOKI-SE:Proc-TIC-001:PT100_TS3',
        topic='loki_misc_devices',
        units='C',
    ),
    '/entry/instrument/thermometer_box_ts4/value': F144Stream(
        nexus_path='/entry/instrument/thermometer_box_ts4/value',
        source='LOKI-SE:Proc-TIC-001:PT100_TS4',
        topic='loki_misc_devices',
        units='C',
    ),
    '/entry/instrument/thermometer_box_ts5/value': F144Stream(
        nexus_path='/entry/instrument/thermometer_box_ts5/value',
        source='LOKI-SE:Proc-TIC-001:PT100_TS5',
        topic='loki_misc_devices',
        units='C',
    ),
    '/entry/instrument/thermometer_box_ts6/value': F144Stream(
        nexus_path='/entry/instrument/thermometer_box_ts6/value',
        source='LOKI-SE:Proc-TIC-001:PT100_TS6',
        topic='loki_misc_devices',
        units='C',
    ),
    '/entry/instrument/thermometer_box_ts7/value': F144Stream(
        nexus_path='/entry/instrument/thermometer_box_ts7/value',
        source='LOKI-SE:Proc-TIC-001:PT100_TS7',
        topic='loki_misc_devices',
        units='C',
    ),
    '/entry/instrument/thermometer_box_ts8/value': F144Stream(
        nexus_path='/entry/instrument/thermometer_box_ts8/value',
        source='LOKI-SE:Proc-TIC-001:PT100_TS8',
        topic='loki_misc_devices',
        units='C',
    ),
    '/entry/instrument/window_guard/value': F144Stream(
        nexus_path='/entry/instrument/window_guard/value',
        source='LOKI-WinGd1:MC-Pne-01:ShtAuxBits07',
        topic='loki_motion',
        units='dimensionless',
    ),
    '/entry/neutron_prod_info/cryo_tt_82025_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82025_temperature',
        source='CrS-CMS:Cryo-TT-82025:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82027_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82027_temperature',
        source='CrS-CMS:Cryo-TT-82027:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82029_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82029_temperature',
        source='CrS-CMS:Cryo-TT-82029:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82031_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82031_temperature',
        source='CrS-CMS:Cryo-TT-82031:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82033_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82033_temperature',
        source='CrS-CMS:Cryo-TT-82033:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/flat_top_current': F144Stream(
        nexus_path='/entry/neutron_prod_info/flat_top_current',
        source='A2T-130LWU:PBI-BCM-001:FlatTopCurrentR',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/neutron_prod_info/fsm_machine_active': F144Stream(
        nexus_path='/entry/neutron_prod_info/fsm_machine_active',
        source='CrS-CMS:SC-FSM-007x:STS_Active',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/neutron_prod_info/pulse_charge': F144Stream(
        nexus_path='/entry/neutron_prod_info/pulse_charge',
        source='A2T-130LWU:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/neutron_prod_info/pulse_width': F144Stream(
        nexus_path='/entry/neutron_prod_info/pulse_width',
        source='A2T-130LWU:PBI-BCM-001:PulseWidthR',
        topic='tn_data_general',
        units='ms',
    ),
}
