# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Scipp contributors (https://github.com/scipp)
"""Auto-generated NeXus f144 stream declarations.

Do not edit by hand. Regenerate with
``python -m ess.livedata.nexus_helpers <geometry.nxs> --generate``.

Source: coda_dream_999999_00003414.hdf
"""

from ess.livedata.config import F144Stream

PARSED_STREAMS: dict[str, F144Stream] = {
    '/entry/instrument/T0_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/T0_chopper/delay',
        source='DREAM-ChpSy2:Chop-T0-101:TotDly',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/T0_chopper/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/T0_chopper/experiment_delay',
        source='DREAM-ChpSy2:Chop-T0-101:ChopDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/T0_chopper/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/T0_chopper/pulse_delay',
        source='DREAM-ChpSy2:Chop-T0-101:BeamPosDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/T0_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/T0_chopper/rotation_speed',
        source='DREAM-ChpSy2:Chop-T0-101:Spd_R',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/T0_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/T0_chopper/rotation_speed_setpoint',
        source='DREAM-ChpSy2:Chop-T0-101:Spd_S',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/band_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/band_chopper/delay',
        source='DREAM-ChpSy1:Chop-BC-201:TotDly',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/band_chopper/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/band_chopper/experiment_delay',
        source='DREAM-ChpSy1:Chop-BC-201:ChopDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/band_chopper/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/band_chopper/pulse_delay',
        source='DREAM-ChpSy1:Chop-BC-201:BeamPosDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/band_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/band_chopper/rotation_speed',
        source='DREAM-ChpSy1:Chop-BC-201:Spd_R',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/band_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/band_chopper/rotation_speed_setpoint',
        source='DREAM-ChpSy1:Chop-BC-201:Spd_S',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/overlap_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/delay',
        source='DREAM-ChpSy1:Chop-OC-103:TotDly',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/overlap_chopper/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/experiment_delay',
        source='DREAM-ChpSy1:Chop-OC-103:ChopDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/overlap_chopper/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/pulse_delay',
        source='DREAM-ChpSy1:Chop-OC-103:BeamPosDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/overlap_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/rotation_speed',
        source='DREAM-ChpSy1:Chop-OC-103:Spd_R',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/overlap_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/rotation_speed_setpoint',
        source='DREAM-ChpSy1:Chop-OC-103:Spd_S',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/polarizer/rate': F144Stream(
        nexus_path='/entry/instrument/polarizer/rate',
        source='SIM_dream:instrument:polarizer:rate',
        topic='dream_nicos_devices',
        units='Hz',
    ),
    '/entry/instrument/pulse_shaping_chopper1/delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper1/delay',
        source='DREAM-ChpSy1:Chop-PSC-101:TotDly',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shaping_chopper1/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper1/experiment_delay',
        source='DREAM-ChpSy1:Chop-PSC-101:ChopDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shaping_chopper1/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper1/pulse_delay',
        source='DREAM-ChpSy1:Chop-PSC-101:BeamPosDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shaping_chopper1/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper1/rotation_speed',
        source='DREAM-ChpSy1:Chop-PSC-101:Spd_R',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/pulse_shaping_chopper1/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper1/rotation_speed_setpoint',
        source='DREAM-ChpSy1:Chop-PSC-101:Spd_S',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/pulse_shaping_chopper2/delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper2/delay',
        source='DREAM-ChpSy1:Chop-PSC-102:TotDly',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shaping_chopper2/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper2/experiment_delay',
        source='DREAM-ChpSy1:Chop-PSC-102:ChopDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shaping_chopper2/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper2/pulse_delay',
        source='DREAM-ChpSy1:Chop-PSC-102:BeamPosDly-S',
        topic='dream_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shaping_chopper2/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper2/rotation_speed',
        source='DREAM-ChpSy1:Chop-PSC-102:Spd_R',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/pulse_shaping_chopper2/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper2/rotation_speed_setpoint',
        source='DREAM-ChpSy1:Chop-PSC-102:Spd_S',
        topic='dream_choppers',
        units='1/s',
    ),
    '/entry/instrument/slit_set_1/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_bottom/idle_flag',
        source='DREAM-ColSl1:MC-SlZm-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_bottom/target_value',
        source='DREAM-ColSl1:MC-SlZm-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_bottom/value',
        source='DREAM-ColSl1:MC-SlZm-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_left/idle_flag',
        source='DREAM-ColSl1:MC-SlYp-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_left/target_value',
        source='DREAM-ColSl1:MC-SlYp-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_left/value',
        source='DREAM-ColSl1:MC-SlYp-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_right/idle_flag',
        source='DREAM-ColSl1:MC-SlYm-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_right/target_value',
        source='DREAM-ColSl1:MC-SlYm-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_right/value',
        source='DREAM-ColSl1:MC-SlYm-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_top/idle_flag',
        source='DREAM-ColSl1:MC-SlZp-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_top/target_value',
        source='DREAM-ColSl1:MC-SlZp-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_top/value',
        source='DREAM-ColSl1:MC-SlZp-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_bottom/idle_flag',
        source='DREAM-ColSl2:MC-SlZm-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_bottom/target_value',
        source='DREAM-ColSl2:MC-SlZm-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_bottom/value',
        source='DREAM-ColSl2:MC-SlZm-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_left/idle_flag',
        source='DREAM-ColSl2:MC-SlYp-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_left/target_value',
        source='DREAM-ColSl2:MC-SlYp-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_left/value',
        source='DREAM-ColSl2:MC-SlYp-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_right/idle_flag',
        source='DREAM-ColSl2:MC-SlYm-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_right/target_value',
        source='DREAM-ColSl2:MC-SlYm-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_right/value',
        source='DREAM-ColSl2:MC-SlYm-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_top/idle_flag',
        source='DREAM-ColSl2:MC-SlZp-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_top/target_value',
        source='DREAM-ColSl2:MC-SlZp-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_top/value',
        source='DREAM-ColSl2:MC-SlZp-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_bottom/idle_flag',
        source='DREAM-ColSl3:MC-SlZm-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_3/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_bottom/target_value',
        source='DREAM-ColSl3:MC-SlZm-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_bottom/value',
        source='DREAM-ColSl3:MC-SlZm-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_left/idle_flag',
        source='DREAM-ColSl3:MC-SlYp-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_3/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_left/target_value',
        source='DREAM-ColSl3:MC-SlYp-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_left/value',
        source='DREAM-ColSl3:MC-SlYp-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_right/idle_flag',
        source='DREAM-ColSl3:MC-SlYm-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_3/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_right/target_value',
        source='DREAM-ColSl3:MC-SlYm-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_right/value',
        source='DREAM-ColSl3:MC-SlYm-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_top/idle_flag',
        source='DREAM-ColSl3:MC-SlZp-01:PzMtr.DMOV',
        topic='dream_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_3/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_top/target_value',
        source='DREAM-ColSl3:MC-SlZp-01:PzMtr.VAL',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/blade_top/value',
        source='DREAM-ColSl3:MC-SlZp-01:PzMtr.RBV',
        topic='dream_motion',
        units='mm',
    ),
    '/entry/instrument/source/current': F144Stream(
        nexus_path='/entry/instrument/source/current',
        source='SIM_dream:instrument:source:current',
        topic='dream_nicos_devices',
        units='mA',
    ),
    '/entry/neutron_prod_info/cryo_tt_82025_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82025_temperature',
        source='CrS-CMS:Cryo-TT-82025:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82027_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82027_temperature',
        source='CrS-CMS:Cryo-TT-82027:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82029_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82029_temperature',
        source='CrS-CMS:Cryo-TT-82029:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82031_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82031_temperature',
        source='CrS-CMS:Cryo-TT-82031:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82033_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82033_temperature',
        source='CrS-CMS:Cryo-TT-82033:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/flat_top_current': F144Stream(
        nexus_path='/entry/neutron_prod_info/flat_top_current',
        source='A2T-130LWU:PBI-BCM-001:FlatTopCurrentR',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/neutron_prod_info/fsm_machine_active': F144Stream(
        nexus_path='/entry/neutron_prod_info/fsm_machine_active',
        source='CrS-CMS:SC-FSM-007x:STS_Active',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/neutron_prod_info/pulse_charge': F144Stream(
        nexus_path='/entry/neutron_prod_info/pulse_charge',
        source='A2T-130LWU:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/neutron_prod_info/pulse_width': F144Stream(
        nexus_path='/entry/neutron_prod_info/pulse_width',
        source='A2T-130LWU:PBI-BCM-001:PulseWidthR',
        topic='tn_data_general',
        units='ms',
    ),
}
