# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Scipp contributors (https://github.com/scipp)
"""
Tracker for pending commands awaiting acknowledgement from backend services.

This module helps correlate command acknowledgements with the original commands
sent by the frontend, enabling proper error handling and UI feedback.
"""

import time
from dataclasses import dataclass
from typing import Literal

from ..config.workflow_spec import WorkflowId

CommandAction = Literal["start", "stop", "reset"]


@dataclass(frozen=True)
class PendingCommand:
    """A command awaiting acknowledgement."""

    workflow_id: WorkflowId
    action: CommandAction
    timestamp: float  # Time when command was sent


class PendingCommandTracker:
    """
    Tracks pending commands awaiting acknowledgement from backend services.

    This class encapsulates the mapping from message_id to pending command info,
    allowing the JobOrchestrator to correlate acknowledgement responses with
    original commands.
    """

    def __init__(self) -> None:
        self._pending: dict[str, PendingCommand] = {}

    def register(
        self, message_id: str, workflow_id: WorkflowId, action: CommandAction
    ) -> None:
        """
        Register a command as pending acknowledgement.

        Parameters
        ----------
        message_id:
            Unique identifier for the command (UUID generated by frontend).
        workflow_id:
            Workflow that the command targets.
        action:
            Type of action being performed.
        """
        self._pending[message_id] = PendingCommand(
            workflow_id=workflow_id,
            action=action,
            timestamp=time.time(),
        )

    def resolve(self, message_id: str) -> PendingCommand | None:
        """
        Resolve a pending command by its message_id.

        Removes the command from pending tracking and returns its info.

        Parameters
        ----------
        message_id:
            The message_id from the acknowledgement response.

        Returns
        -------
        :
            The pending command info, or None if not found.
        """
        return self._pending.pop(message_id, None)

    def expire_stale(self, max_age_seconds: float) -> list[PendingCommand]:
        """
        Remove and return commands that have been pending longer than max_age.

        Parameters
        ----------
        max_age_seconds:
            Maximum time in seconds a command can be pending.

        Returns
        -------
        :
            List of expired commands that were removed.
        """
        current_time = time.time()
        expired = []
        expired_ids = []

        for message_id, cmd in self._pending.items():
            if current_time - cmd.timestamp > max_age_seconds:
                expired.append(cmd)
                expired_ids.append(message_id)

        for message_id in expired_ids:
            del self._pending[message_id]

        return expired

    def __len__(self) -> int:
        """Return number of pending commands."""
        return len(self._pending)
