# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Scipp contributors (https://github.com/scipp)
"""Auto-generated NeXus f144 stream declarations.

Do not edit by hand. Regenerate with
``python -m ess.livedata.nexus_helpers <geometry.nxs> --generate``.

Source: coda_estia_999999_00024007.hdf
"""

from ess.livedata.config import F144Stream

PARSED_STREAMS: dict[str, F144Stream] = {
    '/entry/instrument/analyzer_stage/analyzer_adjustment/idle_flag': F144Stream(
        nexus_path='/entry/instrument/analyzer_stage/analyzer_adjustment/idle_flag',
        source='ESTIA-AnRot:MC-RotY01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/analyzer_stage/analyzer_adjustment/target_value': F144Stream(
        nexus_path='/entry/instrument/analyzer_stage/analyzer_adjustment/target_value',
        source='ESTIA-AnRot:MC-RotY01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/analyzer_stage/analyzer_adjustment/value': F144Stream(
        nexus_path='/entry/instrument/analyzer_stage/analyzer_adjustment/value',
        source='ESTIA-AnRot:MC-RotY01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/analyzer_stage/analyzer_lift/idle_flag': F144Stream(
        nexus_path='/entry/instrument/analyzer_stage/analyzer_lift/idle_flag',
        source='ESTIA-AnLft:MC-LinZ01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/analyzer_stage/analyzer_lift/target_value': F144Stream(
        nexus_path='/entry/instrument/analyzer_stage/analyzer_lift/target_value',
        source='ESTIA-AnLft:MC-LinZ01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/analyzer_stage/analyzer_lift/value': F144Stream(
        nexus_path='/entry/instrument/analyzer_stage/analyzer_lift/value',
        source='ESTIA-AnLft:MC-LinZ01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/bwc/delay': F144Stream(
        nexus_path='/entry/instrument/bwc/delay',
        source='ESTIA-ChpSy1:Chop-BWC-101:TotDly',
        topic='estia_choppers',
        units='ns',
    ),
    '/entry/instrument/bwc/park_angle': F144Stream(
        nexus_path='/entry/instrument/bwc/park_angle',
        source='ESTIA-ChpSy1:Chop-BWC-101:Pos_R',
        topic='estia_choppers',
        units='degrees',
    ),
    '/entry/instrument/bwc/park_control': F144Stream(
        nexus_path='/entry/instrument/bwc/park_control',
        source='ESTIA-ChpSy1:Chop-BWC-101:ParkPos_S',
        topic='estia_choppers',
        units='degrees',
    ),
    '/entry/instrument/bwc/phase': F144Stream(
        nexus_path='/entry/instrument/bwc/phase',
        source='ESTIA-ChpSy1:Chop-BWC-101:InPhs_R',
        topic='estia_choppers',
        units='dimensionless',
    ),
    '/entry/instrument/bwc/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/bwc/rotation_speed',
        source='ESTIA-ChpSy1:Chop-BWC-101:Spd_R',
        topic='estia_choppers',
        units='Hz',
    ),
    '/entry/instrument/bwc/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/bwc/rotation_speed_setpoint',
        source='ESTIA-ChpSy1:Chop-BWC-101:Spd_S',
        topic='estia_choppers',
        units='Hz',
    ),
    '/entry/instrument/bwc/status': F144Stream(
        nexus_path='/entry/instrument/bwc/status',
        source='ESTIA-ChpSy1:Chop-BWC-101:ChopState_R',
        topic='estia_choppers',
        units='dimensionless',
    ),
    '/entry/instrument/detector_arm_rotation/idle_flag': F144Stream(
        nexus_path='/entry/instrument/detector_arm_rotation/idle_flag',
        source='ESTIA-DtRot:MC-RotZ01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/detector_arm_rotation/target_value': F144Stream(
        nexus_path='/entry/instrument/detector_arm_rotation/target_value',
        source='ESTIA-DtRot:MC-RotZ01:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/detector_arm_rotation/value': F144Stream(
        nexus_path='/entry/instrument/detector_arm_rotation/value',
        source='ESTIA-DtRot:MC-RotZ01:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/middle_focus_changer/horizontal_adjustment/idle_flag': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/middle_focus_changer/horizontal_adjustment/idle_flag',
        source='ESTIA-Chg:MC-LinY01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/middle_focus_changer/horizontal_adjustment/target_value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/middle_focus_changer/horizontal_adjustment/target_value',
        source='ESTIA-Chg:MC-LinY01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/middle_focus_changer/horizontal_adjustment/value': F144Stream(
        nexus_path='/entry/instrument/middle_focus_changer/horizontal_adjustment/value',
        source='ESTIA-Chg:MC-LinY01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/middle_focus_changer/mask_changer/idle_flag': F144Stream(
        nexus_path='/entry/instrument/middle_focus_changer/mask_changer/idle_flag',
        source='ESTIA-Chg:MC-RotX01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/middle_focus_changer/mask_changer/target_value': F144Stream(
        nexus_path='/entry/instrument/middle_focus_changer/mask_changer/target_value',
        source='ESTIA-Chg:MC-RotX01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/middle_focus_changer/mask_changer/value': F144Stream(
        nexus_path='/entry/instrument/middle_focus_changer/mask_changer/value',
        source='ESTIA-Chg:MC-RotX01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/middle_focus_changer/vertical_adjustment/idle_flag': F144Stream(
        nexus_path='/entry/instrument/middle_focus_changer/vertical_adjustment/idle_flag',
        source='ESTIA-Chg:MC-LinZ01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/middle_focus_changer/vertical_adjustment/target_value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/middle_focus_changer/vertical_adjustment/target_value',
        source='ESTIA-Chg:MC-LinZ01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/middle_focus_changer/vertical_adjustment/value': F144Stream(
        nexus_path='/entry/instrument/middle_focus_changer/vertical_adjustment/value',
        source='ESTIA-Chg:MC-LinZ01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/polarizer_stage/angle_adjustment/idle_flag': F144Stream(
        nexus_path='/entry/instrument/polarizer_stage/angle_adjustment/idle_flag',
        source='ESTIA-PolChg:MC-RotZ01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/polarizer_stage/angle_adjustment/target_value': F144Stream(
        nexus_path='/entry/instrument/polarizer_stage/angle_adjustment/target_value',
        source='ESTIA-PolChg:MC-RotZ01:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/polarizer_stage/angle_adjustment/value': F144Stream(
        nexus_path='/entry/instrument/polarizer_stage/angle_adjustment/value',
        source='ESTIA-PolChg:MC-RotZ01:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/polarizer_stage/in_beam_changer/idle_flag': F144Stream(
        nexus_path='/entry/instrument/polarizer_stage/in_beam_changer/idle_flag',
        source='ESTIA-PolChg:MC-LinY01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/polarizer_stage/in_beam_changer/target_value': F144Stream(
        nexus_path='/entry/instrument/polarizer_stage/in_beam_changer/target_value',
        source='ESTIA-PolChg:MC-LinY01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/polarizer_stage/in_beam_changer/value': F144Stream(
        nexus_path='/entry/instrument/polarizer_stage/in_beam_changer/value',
        source='ESTIA-PolChg:MC-LinY01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_axis/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_axis/idle_flag',
        source='ESTIA-SpSt:MC-LinY-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_axis/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_axis/target_value',
        source='ESTIA-SpSt:MC-LinY-01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_axis/value': F144Stream(
        nexus_path='/entry/instrument/sample_axis/value',
        source='ESTIA-SpSt:MC-LinY-01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_slit/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_bottom/idle_flag',
        source='ESTIA-SpSl:MC-SlZm:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_slit/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_bottom/target_value',
        source='ESTIA-SpSl:MC-SlZm:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_slit/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_bottom/value',
        source='ESTIA-SpSl:MC-SlZm:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_slit/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_left/idle_flag',
        source='ESTIA-SpSl:MC-SlYp:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_slit/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_left/target_value',
        source='ESTIA-SpSl:MC-SlYp:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_slit/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_left/value',
        source='ESTIA-SpSl:MC-SlYp:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_slit/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_right/idle_flag',
        source='ESTIA-SpSl:MC-SlYm:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_slit/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_right/target_value',
        source='ESTIA-SpSl:MC-SlYm:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_slit/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_right/value',
        source='ESTIA-SpSl:MC-SlYm:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_slit/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_top/idle_flag',
        source='ESTIA-SpSl:MC-SlZp:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_slit/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_top/target_value',
        source='ESTIA-SpSl:MC-SlZp:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_slit/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/sample_slit/blade_top/value',
        source='ESTIA-SpSl:MC-SlZp:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stage/goniometer/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stage/goniometer/idle_flag',
        source='ESTIA-SpRot:MC-RotZ01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stage/goniometer/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/goniometer/target_value',
        source='ESTIA-SpRot:MC-RotZ01:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/sample_stage/goniometer/value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/goniometer/value',
        source='ESTIA-SpRot:MC-RotZ01:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/sample_stage/hexapod/rx/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/rx/idle_flag',
        source='ESTIA-SES:MC-MCU-001:m4.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stage/hexapod/rx/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/rx/target_value',
        source='ESTIA-SES:MC-MCU-001:m4.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/sample_stage/hexapod/rx/value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/rx/value',
        source='ESTIA-SES:MC-MCU-001:m4.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/sample_stage/hexapod/ry/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/ry/idle_flag',
        source='ESTIA-SES:MC-MCU-001:m5.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stage/hexapod/ry/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/ry/target_value',
        source='ESTIA-SES:MC-MCU-001:m5.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/sample_stage/hexapod/ry/value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/ry/value',
        source='ESTIA-SES:MC-MCU-001:m5.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/sample_stage/hexapod/rz/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/rz/idle_flag',
        source='ESTIA-SES:MC-MCU-001:m6.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stage/hexapod/rz/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/rz/target_value',
        source='ESTIA-SES:MC-MCU-001:m6.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/sample_stage/hexapod/rz/value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/rz/value',
        source='ESTIA-SES:MC-MCU-001:m6.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/sample_stage/hexapod/tx/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/tx/idle_flag',
        source='ESTIA-SES:MC-MCU-001:m1.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stage/hexapod/tx/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/tx/target_value',
        source='ESTIA-SES:MC-MCU-001:m1.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stage/hexapod/tx/value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/tx/value',
        source='ESTIA-SES:MC-MCU-001:m1.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stage/hexapod/ty/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/ty/idle_flag',
        source='ESTIA-SES:MC-MCU-001:m2.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stage/hexapod/ty/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/ty/target_value',
        source='ESTIA-SES:MC-MCU-001:m2.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stage/hexapod/ty/value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/ty/value',
        source='ESTIA-SES:MC-MCU-001:m2.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stage/hexapod/tz/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/tz/idle_flag',
        source='ESTIA-SES:MC-MCU-001:m3.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stage/hexapod/tz/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/tz/target_value',
        source='ESTIA-SES:MC-MCU-001:m3.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stage/hexapod/tz/value': F144Stream(
        nexus_path='/entry/instrument/sample_stage/hexapod/tz/value',
        source='ESTIA-SES:MC-MCU-001:m3.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/selene_guide_1/mover_s1/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s1/idle_flag',
        source='ESTIA-SG1SM:MC-RotX-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_1/mover_s1/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s1/target_value',
        source='ESTIA-SG1SM:MC-RotX-01:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1/mover_s1/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s1/value',
        source='ESTIA-SG1SM:MC-RotX-01:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1/mover_s2/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s2/idle_flag',
        source='ESTIA-SG1SM:MC-RotX-02:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_1/mover_s2/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s2/target_value',
        source='ESTIA-SG1SM:MC-RotX-02:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1/mover_s2/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s2/value',
        source='ESTIA-SG1SM:MC-RotX-02:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1/mover_s3/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s3/idle_flag',
        source='ESTIA-SG1SM:MC-RotX-03:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_1/mover_s3/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s3/target_value',
        source='ESTIA-SG1SM:MC-RotX-03:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1/mover_s3/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s3/value',
        source='ESTIA-SG1SM:MC-RotX-03:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1/mover_s4/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s4/idle_flag',
        source='ESTIA-SG1DM:MC-RotX-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_1/mover_s4/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s4/target_value',
        source='ESTIA-SG1DM:MC-RotX-01:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1/mover_s4/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s4/value',
        source='ESTIA-SG1DM:MC-RotX-01:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1/mover_s5/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s5/idle_flag',
        source='ESTIA-SG1DM:MC-RotX-02:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_1/mover_s5/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s5/target_value',
        source='ESTIA-SG1DM:MC-RotX-02:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1/mover_s5/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_1/mover_s5/value',
        source='ESTIA-SG1DM:MC-RotX-02:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_external_mode/target_value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_external_mode/target_value',
        source='ESTIA:WtrC-TE-001:ExternalSensor-S',
        topic='estia_misc_devices',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_external_mode/value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_external_mode/value',
        source='ESTIA:WtrC-TE-001:ExternalSensor-R',
        topic='estia_misc_devices',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_external_temperature/value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_external_temperature/value',
        source='ESTIA:WtrC-TE-001:TempExtSensor-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_internal_temperature/value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_internal_temperature/value',
        source='ESTIA:WtrC-TE-001:Temperature-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_setpoint/target_value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_setpoint/target_value',
        source='ESTIA:WtrC-TE-001:TemperatureSP1-S',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_setpoint/value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_1_julabo/selene_guide_1_julabo_setpoint/value',
        source='ESTIA:WtrC-TE-001:TemperatureSP1-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/selene_guide_2/mover_s1/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s1/idle_flag',
        source='ESTIA-SG2SM:MC-RotX-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_2/mover_s1/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s1/target_value',
        source='ESTIA-SG2SM:MC-RotX-01:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s1/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s1/value',
        source='ESTIA-SG2SM:MC-RotX-01:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s2/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s2/idle_flag',
        source='ESTIA-SG2SM:MC-RotX-02:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_2/mover_s2/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s2/target_value',
        source='ESTIA-SG2SM:MC-RotX-02:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s2/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s2/value',
        source='ESTIA-SG2SM:MC-RotX-02:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s3/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s3/idle_flag',
        source='ESTIA-SG2SM:MC-RotX-03:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_2/mover_s3/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s3/target_value',
        source='ESTIA-SG2SM:MC-RotX-03:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s3/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s3/value',
        source='ESTIA-SG2SM:MC-RotX-03:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s4/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s4/idle_flag',
        source='ESTIA-SG2DM:MC-RotX-02:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_2/mover_s4/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s4/target_value',
        source='ESTIA-SG2DM:MC-RotX-02:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s4/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s4/value',
        source='ESTIA-SG2DM:MC-RotX-02:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s5/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s5/idle_flag',
        source='ESTIA-SG2DM:MC-RotX-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_2/mover_s5/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s5/target_value',
        source='ESTIA-SG2DM:MC-RotX-01:Mtr.VAL',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s5/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s5/value',
        source='ESTIA-SG2DM:MC-RotX-01:Mtr.RBV',
        topic='estia_motion',
        units='deg',
    ),
    '/entry/instrument/selene_guide_2/mover_s6/idle_flag': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s6/idle_flag',
        source='ESTIA-SG2Mv:MC-LinX-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_2/mover_s6/target_value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s6/target_value',
        source='ESTIA-SG2Mv:MC-LinX-01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/selene_guide_2/mover_s6/value': F144Stream(
        nexus_path='/entry/instrument/selene_guide_2/mover_s6/value',
        source='ESTIA-SG2Mv:MC-LinX-01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_external_mode/target_value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_external_mode/target_value',
        source='ESTIA:WtrC-TE-002:ExternalSensor-S',
        topic='estia_misc_devices',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_external_mode/value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_external_mode/value',
        source='ESTIA:WtrC-TE-002:ExternalSensor-R',
        topic='estia_misc_devices',
        units='dimensionless',
    ),
    '/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_external_temperature/value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_external_temperature/value',
        source='ESTIA:WtrC-TE-002:TempExtSensor-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_internal_temperature/value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_internal_temperature/value',
        source='ESTIA:WtrC-TE-002:Temperature-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_setpoint/target_value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_setpoint/target_value',
        source='ESTIA:WtrC-TE-002:TemperatureSP1-S',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_setpoint/value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/selene_guide_2_julabo/selene_guide_2_julabo_setpoint/value',
        source='ESTIA:WtrC-TE-002:TemperatureSP1-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_01/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_01/value',
        source='ESTIA-SG1Tp:MC-Temp-01:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_02/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_02/value',
        source='ESTIA-SG1Tp:MC-Temp-02:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_03/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_03/value',
        source='ESTIA-SG1Tp:MC-Temp-03:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_04/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_04/value',
        source='ESTIA-SG1Tp:MC-Temp-04:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_05/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_05/value',
        source='ESTIA-SG1Tp:MC-Temp-05:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_06/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_06/value',
        source='ESTIA-SG1Tp:MC-Temp-06:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_07/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_07/value',
        source='ESTIA-SG1Tp:MC-Temp-07:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_08/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_08/value',
        source='ESTIA-SG1Tp:MC-Temp-08:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_09/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_09/value',
        source='ESTIA-SG1Tp:MC-Temp-09:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_10/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_10/value',
        source='ESTIA-SG1Tp:MC-Temp-10:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_11/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_11/value',
        source='ESTIA-SG1Tp:MC-Temp-11:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg1_pt100_12/value': F144Stream(
        nexus_path='/entry/instrument/sg1_pt100_12/value',
        source='ESTIA-SG1Tp:MC-Temp-12:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_01/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_01/value',
        source='ESTIA-SG2Tp:MC-Temp-01:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_02/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_02/value',
        source='ESTIA-SG2Tp:MC-Temp-02:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_03/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_03/value',
        source='ESTIA-SG2Tp:MC-Temp-03:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_04/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_04/value',
        source='ESTIA-SG2Tp:MC-Temp-04:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_05/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_05/value',
        source='ESTIA-SG2Tp:MC-Temp-05:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_06/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_06/value',
        source='ESTIA-SG2Tp:MC-Temp-06:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_07/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_07/value',
        source='ESTIA-SG2Tp:MC-Temp-07:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_08/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_08/value',
        source='ESTIA-SG2Tp:MC-Temp-08:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_09/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_09/value',
        source='ESTIA-SG2Tp:MC-Temp-09:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_10/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_10/value',
        source='ESTIA-SG2Tp:MC-Temp-10:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_11/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_11/value',
        source='ESTIA-SG2Tp:MC-Temp-11:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/sg2_pt100_12/value': F144Stream(
        nexus_path='/entry/instrument/sg2_pt100_12/value',
        source='ESTIA-SG2Tp:MC-Temp-12:Temp',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_julabo/slsc_julabo_external_mode/target_value': F144Stream(
        nexus_path='/entry/instrument/slsc_julabo/slsc_julabo_external_mode/target_value',
        source='ESTIA-SES:WtrC-TE-001:ExternalSensor-S',
        topic='estia_misc_devices',
        units='dimensionless',
    ),
    '/entry/instrument/slsc_julabo/slsc_julabo_external_mode/value': F144Stream(
        nexus_path='/entry/instrument/slsc_julabo/slsc_julabo_external_mode/value',
        source='ESTIA-SES:WtrC-TE-001:ExternalSensor-R',
        topic='estia_misc_devices',
        units='dimensionless',
    ),
    '/entry/instrument/slsc_julabo/slsc_julabo_external_temperature/value': F144Stream(
        nexus_path='/entry/instrument/slsc_julabo/slsc_julabo_external_temperature/value',
        source='ESTIA-SES:WtrC-TE-001:TempExtSensor-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_julabo/slsc_julabo_internal_temperature/value': F144Stream(
        nexus_path='/entry/instrument/slsc_julabo/slsc_julabo_internal_temperature/value',
        source='ESTIA-SES:WtrC-TE-001:Temperature-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_julabo/slsc_julabo_setpoint/target_value': F144Stream(
        nexus_path='/entry/instrument/slsc_julabo/slsc_julabo_setpoint/target_value',
        source='ESTIA-SES:WtrC-TE-001:TemperatureSP1-S',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_julabo/slsc_julabo_setpoint/value': F144Stream(
        nexus_path='/entry/instrument/slsc_julabo/slsc_julabo_setpoint/value',
        source='ESTIA-SES:WtrC-TE-001:TemperatureSP1-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_pt100_01/value': F144Stream(
        nexus_path='/entry/instrument/slsc_pt100_01/value',
        source='ESTIA-SES:SE-Holder-001:TCell1-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_pt100_02/value': F144Stream(
        nexus_path='/entry/instrument/slsc_pt100_02/value',
        source='ESTIA-SES:SE-Holder-001:TCell2-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_pt100_03/value': F144Stream(
        nexus_path='/entry/instrument/slsc_pt100_03/value',
        source='ESTIA-SES:SE-Holder-001:TCell3-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_pt100_04/value': F144Stream(
        nexus_path='/entry/instrument/slsc_pt100_04/value',
        source='ESTIA-SES:SE-Holder-001:TCell4-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_pt100_05/value': F144Stream(
        nexus_path='/entry/instrument/slsc_pt100_05/value',
        source='ESTIA-SES:SE-Holder-001:TCell5-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_pt100_06/value': F144Stream(
        nexus_path='/entry/instrument/slsc_pt100_06/value',
        source='ESTIA-SES:SE-Holder-001:TCell6-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/slsc_pt100_07/value': F144Stream(
        nexus_path='/entry/instrument/slsc_pt100_07/value',
        source='ESTIA-SES:SE-Holder-001:TCell7-R',
        topic='estia_misc_devices',
        units='C',
    ),
    '/entry/instrument/source/beam_cycle_id': F144Stream(
        nexus_path='/entry/instrument/source/beam_cycle_id',
        source='TD-M:Ctrl-EVR-1:DbufCycleId-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_destination': F144Stream(
        nexus_path='/entry/instrument/source/beam_destination',
        source='TD-M:Ctrl-EVR-1:DbufBDest-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_destination_mode': F144Stream(
        nexus_path='/entry/instrument/source/beam_destination_mode',
        source='TD-M:Ctrl-EVR-1:DbufBDest-II',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_present': F144Stream(
        nexus_path='/entry/instrument/source/beam_present',
        source='TD-M:Ctrl-EVR-1:DbufBPresent-II',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_pulse_end_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/beam_pulse_end_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtBPulseEndCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_pulse_end_event_id': F144Stream(
        nexus_path='/entry/instrument/source/beam_pulse_end_event_id',
        source='TD-M:Ctrl-EVR-1:EvtBPulseEndId-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_pulse_start_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/beam_pulse_start_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtBPulseStCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_state': F144Stream(
        nexus_path='/entry/instrument/source/beam_state',
        source='TD-M:Ctrl-EVR-1:DbufBState-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beamdump_pulse_charge_010': F144Stream(
        nexus_path='/entry/instrument/source/beamdump_pulse_charge_010',
        source='DmpL-010Drf:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/source/beamdump_pulse_charge_040': F144Stream(
        nexus_path='/entry/instrument/source/beamdump_pulse_charge_040',
        source='DmpL-040Drf:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/source/bunch_length': F144Stream(
        nexus_path='/entry/instrument/source/bunch_length',
        source='TD-M:Ctrl-EVR-1:DbufBLen-I',
        topic='tn_data_general',
        units='us',
    ),
    '/entry/instrument/source/bunch_pattern': F144Stream(
        nexus_path='/entry/instrument/source/bunch_pattern',
        source='TD-M:Ctrl-EVR-1:DbufTgRast-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/cryo_tt_82025_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82025_temperature',
        source='CrS-CMS:Cryo-TT-82025:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/cryo_tt_82027_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82027_temperature',
        source='CrS-CMS:Cryo-TT-82027:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/cryo_tt_82029_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82029_temperature',
        source='CrS-CMS:Cryo-TT-82029:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/cryo_tt_82031_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82031_temperature',
        source='CrS-CMS:Cryo-TT-82031:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/cryo_tt_82033_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82033_temperature',
        source='CrS-CMS:Cryo-TT-82033:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/current': F144Stream(
        nexus_path='/entry/instrument/source/current',
        source='TD-M:Ctrl-EVR-1:DbufBCurr-I',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/instrument/source/cycle_start_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/cycle_start_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtF14HzCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/data_buffer_sent_offset': F144Stream(
        nexus_path='/entry/instrument/source/data_buffer_sent_offset',
        source='TD-M:Ctrl-SCE-1:DbufSentOffset-SP',
        topic='tn_data_general',
        units='us',
    ),
    '/entry/instrument/source/energy': F144Stream(
        nexus_path='/entry/instrument/source/energy',
        source='TD-M:Ctrl-EVR-1:DbufBEn-I',
        topic='tn_data_general',
        units='keV',
    ),
    '/entry/instrument/source/flat_top_current': F144Stream(
        nexus_path='/entry/instrument/source/flat_top_current',
        source='A2T-130LWU:PBI-BCM-001:FlatTopCurrentR',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/instrument/source/fsm_machine_active': F144Stream(
        nexus_path='/entry/instrument/source/fsm_machine_active',
        source='CrS-CMS:SC-FSM-007x:STS_Active',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/high_beta_flat_top_current': F144Stream(
        nexus_path='/entry/instrument/source/high_beta_flat_top_current',
        source='HEBT-160LWU:PBI-BCM-001:FlatTopCurrentR',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/instrument/source/high_beta_pulse_charge': F144Stream(
        nexus_path='/entry/instrument/source/high_beta_pulse_charge',
        source='HEBT-160LWU:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/source/high_beta_pulse_width': F144Stream(
        nexus_path='/entry/instrument/source/high_beta_pulse_width',
        source='HEBT-160LWU:PBI-BCM-001:PulseWidthR',
        topic='tn_data_general',
        units='us',
    ),
    '/entry/instrument/source/mode': F144Stream(
        nexus_path='/entry/instrument/source/mode',
        source='TD-M:Ctrl-EVR-1:DbufBMod-II',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/ni_acq_start_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/ni_acq_start_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtNiAcqStCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/ni_sync_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/ni_sync_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtNiSyncCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/pulse_charge': F144Stream(
        nexus_path='/entry/instrument/source/pulse_charge',
        source='A2T-130LWU:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/source/pulse_width': F144Stream(
        nexus_path='/entry/instrument/source/pulse_width',
        source='A2T-130LWU:PBI-BCM-001:PulseWidthR',
        topic='tn_data_general',
        units='us',
    ),
    '/entry/instrument/source/target_segment': F144Stream(
        nexus_path='/entry/instrument/source/target_segment',
        source='TD-M:Ctrl-EVR-1:DbufTgSeg-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/spin_flipper_analyzer/value': F144Stream(
        nexus_path='/entry/instrument/spin_flipper_analyzer/value',
        source='tbd2',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/spin_flipper_polarizer/value': F144Stream(
        nexus_path='/entry/instrument/spin_flipper_polarizer/value',
        source='ESTIA:RF-SG-001:Freq-R',
        topic='estia_nicos_devices',
        units='dimensionless',
    ),
    '/entry/instrument/virtual_source_slit/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_bottom/idle_flag',
        source='ESTIA-VSSlN:MC-LinZ-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/virtual_source_slit/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_bottom/target_value',
        source='ESTIA-VSSlN:MC-LinZ-01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/virtual_source_slit/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_bottom/value',
        source='ESTIA-VSSlN:MC-LinZ-01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/virtual_source_slit/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_left/idle_flag',
        source='ESTIA-VSSlN:MC-LinX-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/virtual_source_slit/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_left/target_value',
        source='ESTIA-VSSlN:MC-LinX-01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/virtual_source_slit/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_left/value',
        source='ESTIA-VSSlN:MC-LinX-01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/virtual_source_slit/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_right/idle_flag',
        source='ESTIA-VSSlP:MC-LinX-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/virtual_source_slit/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_right/target_value',
        source='ESTIA-VSSlP:MC-LinX-01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/virtual_source_slit/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_right/value',
        source='ESTIA-VSSlP:MC-LinX-01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/virtual_source_slit/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_top/idle_flag',
        source='ESTIA-VSSlP:MC-LinZ-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/virtual_source_slit/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_top/target_value',
        source='ESTIA-VSSlP:MC-LinZ-01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/virtual_source_slit/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/blade_top/value',
        source='ESTIA-VSSlP:MC-LinZ-01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/virtual_source_slit/rotation_stage/idle_flag': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/rotation_stage/idle_flag',
        source='ESTIA-VSRot:MC-RotZ-01:Mtr.DMOV',
        topic='estia_motion',
        units='dimensionless',
    ),
    '/entry/instrument/virtual_source_slit/rotation_stage/target_value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/rotation_stage/target_value',
        source='ESTIA-VSRot:MC-RotZ-01:Mtr.VAL',
        topic='estia_motion',
        units='mm',
    ),
    '/entry/instrument/virtual_source_slit/rotation_stage/value': F144Stream(
        nexus_path='/entry/instrument/virtual_source_slit/rotation_stage/value',
        source='ESTIA-VSRot:MC-RotZ-01:Mtr.RBV',
        topic='estia_motion',
        units='mm',
    ),
}
