# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Scipp contributors (https://github.com/scipp)
"""Auto-generated NeXus f144 stream declarations.

Do not edit by hand. Regenerate with
``python -m ess.livedata.nexus_helpers <geometry.nxs> --generate``.

Source: coda_bifrost_999999_00002625.hdf
"""

from ess.livedata.config import F144Stream

PARSED_STREAMS: dict[str, F144Stream] = {
    '/entry/instrument/114_sample_stack/goniometer_x_lower/idle_flag': F144Stream(
        nexus_path='/entry/instrument/114_sample_stack/goniometer_x_lower/idle_flag',
        source='BIFRO-SpGon:MC-RotX-01:Mtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/114_sample_stack/goniometer_x_lower/target_value': F144Stream(
        nexus_path='/entry/instrument/114_sample_stack/goniometer_x_lower/target_value',
        source='BIFRO-SpGon:MC-RotX-01:Mtr.VAL',
        topic='bifrost_motion',
        units='degrees',
    ),
    '/entry/instrument/114_sample_stack/goniometer_x_lower/value': F144Stream(
        nexus_path='/entry/instrument/114_sample_stack/goniometer_x_lower/value',
        source='BIFRO-SpGon:MC-RotX-01:Mtr.RBV',
        topic='bifrost_motion',
        units='degrees',
    ),
    '/entry/instrument/114_sample_stack/goniometer_y_upper/idle_flag': F144Stream(
        nexus_path='/entry/instrument/114_sample_stack/goniometer_y_upper/idle_flag',
        source='BIFRO-SpGon:MC-RotY-01:Mtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/114_sample_stack/goniometer_y_upper/target_value': F144Stream(
        nexus_path='/entry/instrument/114_sample_stack/goniometer_y_upper/target_value',
        source='BIFRO-SpGon:MC-RotY-01:Mtr.VAL',
        topic='bifrost_motion',
        units='degrees',
    ),
    '/entry/instrument/114_sample_stack/goniometer_y_upper/value': F144Stream(
        nexus_path='/entry/instrument/114_sample_stack/goniometer_y_upper/value',
        source='BIFRO-SpGon:MC-RotY-01:Mtr.RBV',
        topic='bifrost_motion',
        units='degrees',
    ),
    '/entry/instrument/114_sample_stack/rotation_stage/idle_flag': F144Stream(
        nexus_path='/entry/instrument/114_sample_stack/rotation_stage/idle_flag',
        source='BIFRO-SpRot:MC-RotZ-01:Mtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/114_sample_stack/rotation_stage/target_value': F144Stream(
        nexus_path='/entry/instrument/114_sample_stack/rotation_stage/target_value',
        source='BIFRO-SpRot:MC-RotZ-01:Mtr.VAL',
        topic='bifrost_motion',
        units='degrees',
    ),
    '/entry/instrument/114_sample_stack/rotation_stage/value': F144Stream(
        nexus_path='/entry/instrument/114_sample_stack/rotation_stage/value',
        source='BIFRO-SpRot:MC-RotZ-01:Mtr.RBV',
        topic='bifrost_motion',
        units='degrees',
    ),
    '/entry/instrument/118_slits/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_bottom/idle_flag',
        source='BIFRO-SpSl1:MC-SlZm-01:PzMtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/118_slits/blade_bottom/potentiometer_value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_bottom/potentiometer_value',
        source='BIFRO-SpSl1:MC-SlZm-01:PzMtr-PosReadback',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_bottom/target_value',
        source='BIFRO-SpSl1:MC-SlZm-01:PzMtr.VAL',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_bottom/value',
        source='BIFRO-SpSl1:MC-SlZm-01:PzMtr.RBV',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_left/idle_flag',
        source='BIFRO-SpSl1:MC-SlYp-01:PzMtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/118_slits/blade_left/potentiometer_value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_left/potentiometer_value',
        source='BIFRO-SpSl1:MC-SlYp-01:PzMtr-PosReadback',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_left/target_value',
        source='BIFRO-SpSl1:MC-SlYp-01:PzMtr.VAL',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_left/value',
        source='BIFRO-SpSl1:MC-SlYp-01:PzMtr.RBV',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_right/idle_flag',
        source='BIFRO-SpSl1:MC-SlYm-01:PzMtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/118_slits/blade_right/potentiometer_value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_right/potentiometer_value',
        source='BIFRO-SpSl1:MC-SlYm-01:PzMtr-PosReadback',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_right/target_value',
        source='BIFRO-SpSl1:MC-SlYm-01:PzMtr.VAL',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_right/value',
        source='BIFRO-SpSl1:MC-SlYm-01:PzMtr.RBV',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_top/idle_flag',
        source='BIFRO-SpSl1:MC-SlZp-01:PzMtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/118_slits/blade_top/potentiometer_value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_top/potentiometer_value',
        source='BIFRO-SpSl1:MC-SlZp-01:PzMtr-PosReadback',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_top/target_value',
        source='BIFRO-SpSl1:MC-SlZp-01:PzMtr.VAL',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/118_slits/blade_top/value',
        source='BIFRO-SpSl1:MC-SlZp-01:PzMtr.RBV',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/118_slits/slit_position/value': F144Stream(
        nexus_path='/entry/instrument/118_slits/slit_position/value',
        source='BIFRO-SpSl1:MC-LinX-01:PzMtr-PosReadback',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/bandwidth_chopper_1/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/bandwidth_chopper_1/rotation_speed',
        source='BIFRO-ChpSy2:Chop-BWC-101:Spd_R',
        topic='bifrost_choppers',
        units='Hz',
    ),
    '/entry/instrument/bandwidth_chopper_2/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/bandwidth_chopper_2/rotation_speed',
        source='BIFRO-ChpSy2:Chop-BWC-102:Spd_R',
        topic='bifrost_choppers',
        units='Hz',
    ),
    '/entry/instrument/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/blade_left/idle_flag',
        source='BIFRO-DivSl1:MC-SlYp-01:Mtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/blade_left/target_value',
        source='BIFRO-DivSl1:MC-SlYp-01:Mtr.VAL',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/blade_left/value',
        source='BIFRO-DivSl1:MC-SlYp-01:Mtr.RBV',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/blade_right/idle_flag',
        source='BIFRO-DivSl1:MC-SlYm-01:Mtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/blade_right/target_value',
        source='BIFRO-DivSl1:MC-SlYm-01:Mtr.VAL',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/blade_right/value',
        source='BIFRO-DivSl1:MC-SlYm-01:Mtr.RBV',
        topic='bifrost_motion',
        units='mm',
    ),
    '/entry/instrument/delay': F144Stream(
        nexus_path='/entry/instrument/delay',
        source='BIFRO-ChpSy1:Chop-PSC-101:TotDly',
        topic='bifrost_choppers',
        units='ns',
    ),
    '/entry/instrument/detector_tank_angle/transformations/detector_tank_angle_r0/idle_flag': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/detector_tank_angle/transformations/detector_tank_angle_r0/idle_flag',
        source='BIFRO-DtCar:MC-RotZ-01:Mtr.DMOV',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/detector_tank_angle/transformations/detector_tank_angle_r0/target_value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/detector_tank_angle/transformations/detector_tank_angle_r0/target_value',
        source='BIFRO-DtCar:MC-RotZ-01:Mtr.VAL',
        topic='bifrost_motion',
        units='degrees',
    ),
    '/entry/instrument/detector_tank_angle/transformations/detector_tank_angle_r0/value': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/detector_tank_angle/transformations/detector_tank_angle_r0/value',
        source='BIFRO-DtCar:MC-RotZ-01:Mtr.RBV',
        topic='bifrost_motion',
        units='degrees',
    ),
    '/entry/instrument/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/experiment_delay',
        source='BIFRO-ChpSy1:Chop-PSC-101:ChopDly-S',
        topic='bifrost_choppers',
        units='ns',
    ),
    '/entry/instrument/frame_overlap_chopper_1/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/frame_overlap_chopper_1/rotation_speed',
        source='BIFRO-ChpSy1:Chop-FOC-101:Spd_R',
        topic='bifrost_choppers',
        units='Hz',
    ),
    '/entry/instrument/frame_overlap_chopper_2/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/frame_overlap_chopper_2/rotation_speed',
        source='BIFRO-ChpSy1:Chop-FOC-201:Spd_R',
        topic='bifrost_choppers',
        units='Hz',
    ),
    '/entry/instrument/get_lost_tube/status': F144Stream(
        nexus_path='/entry/instrument/get_lost_tube/status',
        source='BIFRO-InBm:MC-Pne-01:ShtAuxBits07',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/instrument/mechanical_delay': F144Stream(
        nexus_path='/entry/instrument/mechanical_delay',
        source='BIFRO-ChpSy1:Chop-PSC-101:MechDly-S',
        topic='bifrost_choppers',
        units='degrees',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82025_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82025_temperature',
        source='CrS-CMS:Cryo-TT-82025:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82027_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82027_temperature',
        source='CrS-CMS:Cryo-TT-82027:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82029_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82029_temperature',
        source='CrS-CMS:Cryo-TT-82029:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82031_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82031_temperature',
        source='CrS-CMS:Cryo-TT-82031:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82033_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82033_temperature',
        source='CrS-CMS:Cryo-TT-82033:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/flat_top_current': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/flat_top_current',
        source='A2T-130LWU:PBI-BCM-001:FlatTopCurrentR',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/instrument/neutron_prod_info/fsm_machine_active': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/fsm_machine_active',
        source='CrS-CMS:SC-FSM-007x:STS_Active',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/neutron_prod_info/pulse_charge': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/pulse_charge',
        source='A2T-130LWU:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/neutron_prod_info/pulse_width': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/pulse_width',
        source='A2T-130LWU:PBI-BCM-001:PulseWidthR',
        topic='tn_data_general',
        units='ms',
    ),
    '/entry/instrument/park_angle': F144Stream(
        nexus_path='/entry/instrument/park_angle',
        source='BIFRO-ChpSy1:Chop-PSC-101:Pos_R',
        topic='bifrost_choppers',
        units='degrees',
    ),
    '/entry/instrument/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_delay',
        source='BIFRO-ChpSy1:Chop-PSC-101:BeamPosDly-S',
        topic='bifrost_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shaping_chopper_1/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper_1/rotation_speed',
        source='BIFRO-ChpSy1:Chop-PSC-101:Spd_R',
        topic='bifrost_choppers',
        units='Hz',
    ),
    '/entry/instrument/pulse_shaping_chopper_2/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/pulse_shaping_chopper_2/rotation_speed',
        source='BIFRO-ChpSy1:Chop-PSC-102:Spd_R',
        topic='bifrost_choppers',
        units='Hz',
    ),
    '/entry/instrument/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/rotation_speed_setpoint',
        source='BIFRO-ChpSy1:Chop-PSC-101:Spd_S',
        topic='bifrost_choppers',
        units='Hz',
    ),
    '/entry/instrument/status': F144Stream(
        nexus_path='/entry/instrument/status',
        source='BIFRO-AttChg:MC-Pne-01:ShtAuxBits07',
        topic='bifrost_motion',
        units='dimensionless',
    ),
    '/entry/sample/sample_environment/HTR1/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/HTR1/value_log',
        source='YMIR-SEE:SE-LS336-004:HTR1',
        topic='bifrost_sample_env',
        units='W',
    ),
    '/entry/sample/sample_environment/HTR2/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/HTR2/value_log',
        source='YMIR-SEE:SE-LS336-004:HTR2',
        topic='bifrost_sample_env',
        units='W',
    ),
    '/entry/sample/sample_environment/KRDG0/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/KRDG0/value_log',
        source='YMIR-SEE:SE-LS336-004:KRDG0',
        topic='bifrost_sample_env',
        units='K',
    ),
    '/entry/sample/sample_environment/KRDG1/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/KRDG1/value_log',
        source='YMIR-SEE:SE-LS336-004:KRDG1',
        topic='bifrost_sample_env',
        units='K',
    ),
    '/entry/sample/sample_environment/KRDG2/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/KRDG2/value_log',
        source='YMIR-SEE:SE-LS336-004:KRDG2',
        topic='bifrost_sample_env',
        units='K',
    ),
    '/entry/sample/sample_environment/KRDG3/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/KRDG3/value_log',
        source='YMIR-SEE:SE-LS336-004:KRDG3',
        topic='bifrost_sample_env',
        units='K',
    ),
    '/entry/sample/sample_environment/SETP_S1': F144Stream(
        nexus_path='/entry/sample/sample_environment/SETP_S1',
        source='YMIR-SEE:SE-LS336-004:SETP_S1',
        topic='bifrost_sample_env',
        units='K',
    ),
    '/entry/sample/sample_environment/SETP_S2': F144Stream(
        nexus_path='/entry/sample/sample_environment/SETP_S2',
        source='YMIR-SEE:SE-LS336-004:SETP_S2',
        topic='bifrost_sample_env',
        units='K',
    ),
    '/entry/sample/sample_environment/SETP_S3': F144Stream(
        nexus_path='/entry/sample/sample_environment/SETP_S3',
        source='YMIR-SEE:SE-LS336-004:SETP_S3',
        topic='bifrost_sample_env',
        units='K',
    ),
    '/entry/sample/sample_environment/SETP_S4': F144Stream(
        nexus_path='/entry/sample/sample_environment/SETP_S4',
        source='YMIR-SEE:SE-LS336-004:SETP_S4',
        topic='bifrost_sample_env',
        units='K',
    ),
    '/entry/sample/sample_environment/SRDG0/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/SRDG0/value_log',
        source='YMIR-SEE:SE-LS336-004:SRDG0',
        topic='bifrost_sample_env',
        units='V',
    ),
    '/entry/sample/sample_environment/SRDG1/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/SRDG1/value_log',
        source='YMIR-SEE:SE-LS336-004:SRDG1',
        topic='bifrost_sample_env',
        units='V',
    ),
    '/entry/sample/sample_environment/SRDG2/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/SRDG2/value_log',
        source='YMIR-SEE:SE-LS336-004:SRDG2',
        topic='bifrost_sample_env',
        units='V',
    ),
    '/entry/sample/sample_environment/SRDG3/value_log': F144Stream(
        nexus_path='/entry/sample/sample_environment/SRDG3/value_log',
        source='YMIR-SEE:SE-LS336-004:SRDG3',
        topic='bifrost_sample_env',
        units='V',
    ),
}
