# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Scipp contributors (https://github.com/scipp)
"""Auto-generated NeXus f144 stream declarations.

Do not edit by hand. Regenerate with
``python -m ess.livedata.nexus_helpers <geometry.nxs> --generate``.

Source: coda_tbl_999999_00024013.hdf
"""

from ess.livedata.config import F144Stream

PARSED_STREAMS: dict[str, F144Stream] = {
    '/entry/instrument/attentuator/position_readback': F144Stream(
        nexus_path='/entry/instrument/attentuator/position_readback',
        source='TBL-AttChg:MC-LinY-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/attentuator/position_setpoint': F144Stream(
        nexus_path='/entry/instrument/attentuator/position_setpoint',
        source='TBL-AttChg:MC-LinY-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/bwc_1/delay': F144Stream(
        nexus_path='/entry/instrument/bwc_1/delay',
        source='TBL-ChpSy1:Chop-BWC-101:TotDly',
        topic='tbl_choppers',
        units='ns',
    ),
    '/entry/instrument/bwc_1/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/bwc_1/experiment_delay',
        source='TBL-ChpSy1:Chop-BWC-101:ChopDly-S',
        topic='tbl_choppers',
        units='ns',
    ),
    '/entry/instrument/bwc_1/mechanical_delay': F144Stream(
        nexus_path='/entry/instrument/bwc_1/mechanical_delay',
        source='TBL-ChpSy1:Chop-BWC-101:MechDly-S',
        topic='tbl_choppers',
        units='degrees',
    ),
    '/entry/instrument/bwc_1/park_angle': F144Stream(
        nexus_path='/entry/instrument/bwc_1/park_angle',
        source='TBL-ChpSy1:Chop-BWC-101:Pos_R',
        topic='tbl_choppers',
        units='degrees',
    ),
    '/entry/instrument/bwc_1/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/bwc_1/pulse_delay',
        source='TBL-ChpSy1:Chop-BWC-101:BeamPosDly-S',
        topic='tbl_choppers',
        units='ns',
    ),
    '/entry/instrument/bwc_1/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/bwc_1/rotation_speed',
        source='TBL-ChpSy1:Chop-BWC-101:Spd_R',
        topic='tbl_choppers',
        units='Hz',
    ),
    '/entry/instrument/bwc_1/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/bwc_1/rotation_speed_setpoint',
        source='TBL-ChpSy1:Chop-BWC-101:Spd_S',
        topic='tbl_choppers',
        units='Hz',
    ),
    '/entry/instrument/bwc_2/delay': F144Stream(
        nexus_path='/entry/instrument/bwc_2/delay',
        source='TBL-ChpSy1:Chop-BWC-102:TotDly',
        topic='tbl_choppers',
        units='ns',
    ),
    '/entry/instrument/bwc_2/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/bwc_2/experiment_delay',
        source='TBL-ChpSy1:Chop-BWC-102:ChopDly-S',
        topic='tbl_choppers',
        units='ns',
    ),
    '/entry/instrument/bwc_2/mechanical_delay': F144Stream(
        nexus_path='/entry/instrument/bwc_2/mechanical_delay',
        source='TBL-ChpSy1:Chop-BWC-102:MechDly-S',
        topic='tbl_choppers',
        units='degrees',
    ),
    '/entry/instrument/bwc_2/park_angle': F144Stream(
        nexus_path='/entry/instrument/bwc_2/park_angle',
        source='TBL-ChpSy1:Chop-BWC-102:Pos_R',
        topic='tbl_choppers',
        units='degrees',
    ),
    '/entry/instrument/bwc_2/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/bwc_2/pulse_delay',
        source='TBL-ChpSy1:Chop-BWC-102:BeamPosDly-S',
        topic='tbl_choppers',
        units='ns',
    ),
    '/entry/instrument/bwc_2/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/bwc_2/rotation_speed',
        source='TBL-ChpSy1:Chop-BWC-102:Spd_R',
        topic='tbl_choppers',
        units='Hz',
    ),
    '/entry/instrument/bwc_2/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/bwc_2/rotation_speed_setpoint',
        source='TBL-ChpSy1:Chop-BWC-102:Spd_S',
        topic='tbl_choppers',
        units='Hz',
    ),
    '/entry/instrument/camera_stage/idle_flag': F144Stream(
        nexus_path='/entry/instrument/camera_stage/idle_flag',
        source='TBL-TBL:MC-Pos-303:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/camera_stage/target_value': F144Stream(
        nexus_path='/entry/instrument/camera_stage/target_value',
        source='TBL-TBL:MC-Pos-303:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/camera_stage/value': F144Stream(
        nexus_path='/entry/instrument/camera_stage/value',
        source='TBL-TBL:MC-Pos-303:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/collimator_horizontal/position_readback': F144Stream(
        nexus_path='/entry/instrument/collimator_horizontal/position_readback',
        source='TBL-PinLin:MC-LinY-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/collimator_horizontal/position_setpoint': F144Stream(
        nexus_path='/entry/instrument/collimator_horizontal/position_setpoint',
        source='TBL-PinLin:MC-LinY-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/collimator_vertical/position_readback': F144Stream(
        nexus_path='/entry/instrument/collimator_vertical/position_readback',
        source='TBL-PinLif:MC-LinZ-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/collimator_vertical/position_setpoint': F144Stream(
        nexus_path='/entry/instrument/collimator_vertical/position_setpoint',
        source='TBL-PinLif:MC-LinZ-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/filter_1/position_readback': F144Stream(
        nexus_path='/entry/instrument/filter_1/position_readback',
        source='TBL-FilChg:MC-LinY-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/filter_1/position_setpoint': F144Stream(
        nexus_path='/entry/instrument/filter_1/position_setpoint',
        source='TBL-FilChg:MC-LinY-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/filter_2/position_readback': F144Stream(
        nexus_path='/entry/instrument/filter_2/position_readback',
        source='TBL-FilChg:MC-LinY-02:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/filter_2/position_setpoint': F144Stream(
        nexus_path='/entry/instrument/filter_2/position_setpoint',
        source='TBL-FilChg:MC-LinY-02:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/filter_3/position_readback': F144Stream(
        nexus_path='/entry/instrument/filter_3/position_readback',
        source='TBL-FilChg:MC-LinY-03:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/filter_3/position_setpoint': F144Stream(
        nexus_path='/entry/instrument/filter_3/position_setpoint',
        source='TBL-FilChg:MC-LinY-03:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch00_current': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch00_current',
        source='TBL-DtCmn:PwrC-HVM-101:Ch00-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch00_voltage': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch00_voltage',
        source='TBL-DtCmn:PwrC-HVM-101:Ch00-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch01_current': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch01_current',
        source='TBL-DtCmn:PwrC-HVM-101:Ch01-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch01_voltage': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch01_voltage',
        source='TBL-DtCmn:PwrC-HVM-101:Ch01-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch02_current': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch02_current',
        source='TBL-DtCmn:PwrC-HVM-101:Ch02-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch02_voltage': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch02_voltage',
        source='TBL-DtCmn:PwrC-HVM-101:Ch02-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch03_current': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch03_current',
        source='TBL-DtCmn:PwrC-HVM-101:Ch03-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch03_voltage': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank0/he3_bank0_hvps_board101_ch03_voltage',
        source='TBL-DtCmn:PwrC-HVM-101:Ch03-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch00_current': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch00_current',
        source='TBL-DtCmn:PwrC-HVM-102:Ch00-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch00_voltage': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch00_voltage',
        source='TBL-DtCmn:PwrC-HVM-102:Ch00-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch01_current': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch01_current',
        source='TBL-DtCmn:PwrC-HVM-102:Ch01-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch01_voltage': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch01_voltage',
        source='TBL-DtCmn:PwrC-HVM-102:Ch01-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch02_current': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch02_current',
        source='TBL-DtCmn:PwrC-HVM-102:Ch02-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch02_voltage': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch02_voltage',
        source='TBL-DtCmn:PwrC-HVM-102:Ch02-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch03_current': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch03_current',
        source='TBL-DtCmn:PwrC-HVM-102:Ch03-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch03_voltage': F144Stream(  # noqa: E501
        nexus_path='/entry/instrument/he3_detector_bank1/he3_bank1_hvps_board102_ch03_voltage',
        source='TBL-DtCmn:PwrC-HVM-102:Ch03-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/large_slit_horizontal_center/idle_flag': F144Stream(
        nexus_path='/entry/instrument/large_slit_horizontal_center/idle_flag',
        source='TBL-SlL:MC-Yc-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/large_slit_horizontal_center/target_value': F144Stream(
        nexus_path='/entry/instrument/large_slit_horizontal_center/target_value',
        source='TBL-SlL:MC-Yc-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_horizontal_center/value': F144Stream(
        nexus_path='/entry/instrument/large_slit_horizontal_center/value',
        source='TBL-SlL:MC-Yc-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_horizontal_gap/idle_flag': F144Stream(
        nexus_path='/entry/instrument/large_slit_horizontal_gap/idle_flag',
        source='TBL-SlL:MC-Yg-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/large_slit_horizontal_gap/target_value': F144Stream(
        nexus_path='/entry/instrument/large_slit_horizontal_gap/target_value',
        source='TBL-SlL:MC-Yg-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_horizontal_gap/value': F144Stream(
        nexus_path='/entry/instrument/large_slit_horizontal_gap/value',
        source='TBL-SlL:MC-Yg-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/large_slit_left/idle_flag',
        source='TBL-TBL:MC-Pos-408:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/large_slit_left/target_value': F144Stream(
        nexus_path='/entry/instrument/large_slit_left/target_value',
        source='TBL-TBL:MC-Pos-408:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_left/value': F144Stream(
        nexus_path='/entry/instrument/large_slit_left/value',
        source='TBL-TBL:MC-Pos-408:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_lower/idle_flag': F144Stream(
        nexus_path='/entry/instrument/large_slit_lower/idle_flag',
        source='TBL-TBL:MC-Pos-410:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/large_slit_lower/target_value': F144Stream(
        nexus_path='/entry/instrument/large_slit_lower/target_value',
        source='TBL-TBL:MC-Pos-410:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_lower/value': F144Stream(
        nexus_path='/entry/instrument/large_slit_lower/value',
        source='TBL-TBL:MC-Pos-410:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/large_slit_right/idle_flag',
        source='TBL-TBL:MC-Pos-407:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/large_slit_right/target_value': F144Stream(
        nexus_path='/entry/instrument/large_slit_right/target_value',
        source='TBL-TBL:MC-Pos-407:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_right/value': F144Stream(
        nexus_path='/entry/instrument/large_slit_right/value',
        source='TBL-TBL:MC-Pos-407:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_upper/idle_flag': F144Stream(
        nexus_path='/entry/instrument/large_slit_upper/idle_flag',
        source='TBL-TBL:MC-Pos-409:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/large_slit_upper/target_value': F144Stream(
        nexus_path='/entry/instrument/large_slit_upper/target_value',
        source='TBL-TBL:MC-Pos-409:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_upper/value': F144Stream(
        nexus_path='/entry/instrument/large_slit_upper/value',
        source='TBL-TBL:MC-Pos-409:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_vertical_center/idle_flag': F144Stream(
        nexus_path='/entry/instrument/large_slit_vertical_center/idle_flag',
        source='TBL-SlL:MC-Zc-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/large_slit_vertical_center/target_value': F144Stream(
        nexus_path='/entry/instrument/large_slit_vertical_center/target_value',
        source='TBL-SlL:MC-Zc-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_vertical_center/value': F144Stream(
        nexus_path='/entry/instrument/large_slit_vertical_center/value',
        source='TBL-SlL:MC-Zc-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_vertical_gap/idle_flag': F144Stream(
        nexus_path='/entry/instrument/large_slit_vertical_gap/idle_flag',
        source='TBL-SlL:MC-Zg-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/large_slit_vertical_gap/target_value': F144Stream(
        nexus_path='/entry/instrument/large_slit_vertical_gap/target_value',
        source='TBL-SlL:MC-Zg-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/large_slit_vertical_gap/value': F144Stream(
        nexus_path='/entry/instrument/large_slit_vertical_gap/value',
        source='TBL-SlL:MC-Zg-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/linear_x_1/idle_flag': F144Stream(
        nexus_path='/entry/instrument/linear_x_1/idle_flag',
        source='TBL-TBL:MC-Pos-305:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/linear_x_1/target_value': F144Stream(
        nexus_path='/entry/instrument/linear_x_1/target_value',
        source='TBL-TBL:MC-Pos-305:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/linear_x_1/value': F144Stream(
        nexus_path='/entry/instrument/linear_x_1/value',
        source='TBL-TBL:MC-Pos-305:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/linear_x_2/idle_flag': F144Stream(
        nexus_path='/entry/instrument/linear_x_2/idle_flag',
        source='TBL-TBL:MC-Pos-306:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/linear_x_2/target_value': F144Stream(
        nexus_path='/entry/instrument/linear_x_2/target_value',
        source='TBL-TBL:MC-Pos-306:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/linear_x_2/value': F144Stream(
        nexus_path='/entry/instrument/linear_x_2/value',
        source='TBL-TBL:MC-Pos-306:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/linear_x_3/idle_flag': F144Stream(
        nexus_path='/entry/instrument/linear_x_3/idle_flag',
        source='TBL-TBL:MC-Pos-307:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/linear_x_3/target_value': F144Stream(
        nexus_path='/entry/instrument/linear_x_3/target_value',
        source='TBL-TBL:MC-Pos-307:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/linear_x_3/value': F144Stream(
        nexus_path='/entry/instrument/linear_x_3/value',
        source='TBL-TBL:MC-Pos-307:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/linear_z_1/idle_flag': F144Stream(
        nexus_path='/entry/instrument/linear_z_1/idle_flag',
        source='TBL-TBL:MC-Pos-308:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/linear_z_1/target_value': F144Stream(
        nexus_path='/entry/instrument/linear_z_1/target_value',
        source='TBL-TBL:MC-Pos-308:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/linear_z_1/value': F144Stream(
        nexus_path='/entry/instrument/linear_z_1/value',
        source='TBL-TBL:MC-Pos-308:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/medium_rotation/idle_flag': F144Stream(
        nexus_path='/entry/instrument/medium_rotation/idle_flag',
        source='TBL-TBL:MC-Pos-312:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/medium_rotation/target_value': F144Stream(
        nexus_path='/entry/instrument/medium_rotation/target_value',
        source='TBL-TBL:MC-Pos-312:Mtr.VAL',
        topic='tbl_motion',
        units='degrees',
    ),
    '/entry/instrument/medium_rotation/value': F144Stream(
        nexus_path='/entry/instrument/medium_rotation/value',
        source='TBL-TBL:MC-Pos-312:Mtr.RBV',
        topic='tbl_motion',
        units='degrees',
    ),
    '/entry/instrument/monitor_1/hvps_voltage': F144Stream(
        nexus_path='/entry/instrument/monitor_1/hvps_voltage',
        source='TBL-BM:NDet-CDTIBM-001:HighVoltage-R',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/multiblade_detector/mb_hvps_board100_ch00_current': F144Stream(
        nexus_path='/entry/instrument/multiblade_detector/mb_hvps_board100_ch00_current',
        source='TBL-DtCmn:PwrC-HVM-100:Ch00-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/multiblade_detector/mb_hvps_board100_ch00_voltage': F144Stream(
        nexus_path='/entry/instrument/multiblade_detector/mb_hvps_board100_ch00_voltage',
        source='TBL-DtCmn:PwrC-HVM-100:Ch00-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/multiblade_detector/mb_hvps_board100_ch01_current': F144Stream(
        nexus_path='/entry/instrument/multiblade_detector/mb_hvps_board100_ch01_current',
        source='TBL-DtCmn:PwrC-HVM-100:Ch01-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/multiblade_detector/mb_hvps_board100_ch01_voltage': F144Stream(
        nexus_path='/entry/instrument/multiblade_detector/mb_hvps_board100_ch01_voltage',
        source='TBL-DtCmn:PwrC-HVM-100:Ch01-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/multiblade_detector/mb_hvps_board100_ch02_current': F144Stream(
        nexus_path='/entry/instrument/multiblade_detector/mb_hvps_board100_ch02_current',
        source='TBL-DtCmn:PwrC-HVM-100:Ch02-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/multiblade_detector/mb_hvps_board100_ch02_voltage': F144Stream(
        nexus_path='/entry/instrument/multiblade_detector/mb_hvps_board100_ch02_voltage',
        source='TBL-DtCmn:PwrC-HVM-100:Ch02-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/multiblade_detector/mb_hvps_board100_ch03_current': F144Stream(
        nexus_path='/entry/instrument/multiblade_detector/mb_hvps_board100_ch03_current',
        source='TBL-DtCmn:PwrC-HVM-100:Ch03-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/multiblade_detector/mb_hvps_board100_ch03_voltage': F144Stream(
        nexus_path='/entry/instrument/multiblade_detector/mb_hvps_board100_ch03_voltage',
        source='TBL-DtCmn:PwrC-HVM-100:Ch03-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/ngem_detector/ngem_hvps_board103_ch00_current': F144Stream(
        nexus_path='/entry/instrument/ngem_detector/ngem_hvps_board103_ch00_current',
        source='TBL-DtCmn:PwrC-HVM-103:Ch00-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/ngem_detector/ngem_hvps_board103_ch00_voltage': F144Stream(
        nexus_path='/entry/instrument/ngem_detector/ngem_hvps_board103_ch00_voltage',
        source='TBL-DtCmn:PwrC-HVM-103:Ch00-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/ngem_detector/ngem_lvps_board105_ch00_current': F144Stream(
        nexus_path='/entry/instrument/ngem_detector/ngem_lvps_board105_ch00_current',
        source='TBL-DtCmn:PwrC-LVM-105:Ch00-IMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/ngem_detector/ngem_lvps_board105_ch00_voltage': F144Stream(
        nexus_path='/entry/instrument/ngem_detector/ngem_lvps_board105_ch00_voltage',
        source='TBL-DtCmn:PwrC-LVM-105:Ch00-VMon',
        topic='tbl_misc_devices',
        units='V',
    ),
    '/entry/instrument/orca_detector/image_key': F144Stream(
        nexus_path='/entry/instrument/orca_detector/image_key',
        source='orca_image_type',
        topic='tbl_nicos_devices',
        units='dimensionless',
    ),
    '/entry/instrument/orca_detector/intensifier': F144Stream(
        nexus_path='/entry/instrument/orca_detector/intensifier',
        source='TBL-DtCMOS:NDet-ImgInt-001:IntensifierGain-R',
        topic='tbl_misc_devices',
        units='dimensionless',
    ),
    '/entry/instrument/orca_detector/intensifier_gate_delay': F144Stream(
        nexus_path='/entry/instrument/orca_detector/intensifier_gate_delay',
        source='TBL-DtCmn:Ctrl-EVR-001:DlyGen1Delay-RB',
        topic='tbl_misc_devices',
        units='us',
    ),
    '/entry/instrument/orca_detector/intensifier_gate_width': F144Stream(
        nexus_path='/entry/instrument/orca_detector/intensifier_gate_width',
        source='TBL-DtCmn:Ctrl-EVR-001:DlyGen1Width-RB',
        topic='tbl_misc_devices',
        units='us',
    ),
    '/entry/instrument/pinhole/position_readback': F144Stream(
        nexus_path='/entry/instrument/pinhole/position_readback',
        source='TBL-PinChg:MC-LinY-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/pinhole/position_setpoint': F144Stream(
        nexus_path='/entry/instrument/pinhole/position_setpoint',
        source='TBL-PinChg:MC-LinY-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_rotation/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_rotation/idle_flag',
        source='TBL-TBL:MC-Pos-311:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_rotation/target_value': F144Stream(
        nexus_path='/entry/instrument/small_rotation/target_value',
        source='TBL-TBL:MC-Pos-311:Mtr.VAL',
        topic='tbl_motion',
        units='degrees',
    ),
    '/entry/instrument/small_rotation/value': F144Stream(
        nexus_path='/entry/instrument/small_rotation/value',
        source='TBL-TBL:MC-Pos-311:Mtr.RBV',
        topic='tbl_motion',
        units='degrees',
    ),
    '/entry/instrument/small_slit_1_horizontal_center/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_horizontal_center/idle_flag',
        source='TBL-Sl1:MC-Yc-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_1_horizontal_center/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_horizontal_center/target_value',
        source='TBL-Sl1:MC-Yc-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_horizontal_center/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_horizontal_center/value',
        source='TBL-Sl1:MC-Yc-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_horizontal_gap/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_horizontal_gap/idle_flag',
        source='TBL-Sl1:MC-Yg-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_1_horizontal_gap/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_horizontal_gap/target_value',
        source='TBL-Sl1:MC-Yg-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_horizontal_gap/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_horizontal_gap/value',
        source='TBL-Sl1:MC-Yg-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_left/idle_flag',
        source='TBL-TBL:MC-Pos-403:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_1_left/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_left/target_value',
        source='TBL-TBL:MC-Pos-403:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_left/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_left/value',
        source='TBL-TBL:MC-Pos-403:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_lower/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_lower/idle_flag',
        source='TBL-TBL:MC-Pos-405:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_1_lower/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_lower/target_value',
        source='TBL-TBL:MC-Pos-405:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_lower/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_lower/value',
        source='TBL-TBL:MC-Pos-405:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_right/idle_flag',
        source='TBL-TBL:MC-Pos-404:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_1_right/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_right/target_value',
        source='TBL-TBL:MC-Pos-404:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_right/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_right/value',
        source='TBL-TBL:MC-Pos-404:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_upper/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_upper/idle_flag',
        source='TBL-TBL:MC-Pos-406:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_1_upper/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_upper/target_value',
        source='TBL-TBL:MC-Pos-406:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_upper/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_upper/value',
        source='TBL-TBL:MC-Pos-406:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_vertical_center/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_vertical_center/idle_flag',
        source='TBL-Sl1:MC-Zc-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_1_vertical_center/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_vertical_center/target_value',
        source='TBL-Sl1:MC-Zc-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_vertical_center/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_vertical_center/value',
        source='TBL-Sl1:MC-Zc-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_vertical_gap/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_vertical_gap/idle_flag',
        source='TBL-Sl1:MC-Zg-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_1_vertical_gap/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_vertical_gap/target_value',
        source='TBL-Sl1:MC-Zg-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_1_vertical_gap/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_1_vertical_gap/value',
        source='TBL-Sl1:MC-Zg-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_horizontal_center/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_horizontal_center/idle_flag',
        source='TBL-Sl2:MC-Yc-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_2_horizontal_center/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_horizontal_center/target_value',
        source='TBL-Sl2:MC-Yc-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_horizontal_center/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_horizontal_center/value',
        source='TBL-Sl2:MC-Yc-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_horizontal_gap/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_horizontal_gap/idle_flag',
        source='TBL-Sl2:MC-Yg-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_2_horizontal_gap/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_horizontal_gap/target_value',
        source='TBL-Sl2:MC-Yg-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_horizontal_gap/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_horizontal_gap/value',
        source='TBL-Sl2:MC-Yg-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_left/idle_flag',
        source='TBL-TBL:MC-Pos-412:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_2_left/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_left/target_value',
        source='TBL-TBL:MC-Pos-412:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_left/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_left/value',
        source='TBL-TBL:MC-Pos-412:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_lower/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_lower/idle_flag',
        source='TBL-TBL:MC-Pos-414:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_2_lower/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_lower/target_value',
        source='TBL-TBL:MC-Pos-414:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_lower/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_lower/value',
        source='TBL-TBL:MC-Pos-414:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_right/idle_flag',
        source='TBL-TBL:MC-Pos-411:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_2_right/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_right/target_value',
        source='TBL-TBL:MC-Pos-411:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_right/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_right/value',
        source='TBL-TBL:MC-Pos-411:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_upper/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_upper/idle_flag',
        source='TBL-TBL:MC-Pos-413:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_2_upper/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_upper/target_value',
        source='TBL-TBL:MC-Pos-413:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_upper/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_upper/value',
        source='TBL-TBL:MC-Pos-413:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_vertical_center/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_vertical_center/idle_flag',
        source='TBL-Sl2:MC-Zc-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_2_vertical_center/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_vertical_center/target_value',
        source='TBL-Sl2:MC-Zc-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_vertical_center/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_vertical_center/value',
        source='TBL-Sl2:MC-Zc-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_vertical_gap/idle_flag': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_vertical_gap/idle_flag',
        source='TBL-Sl2:MC-Zg-01:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/small_slit_2_vertical_gap/target_value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_vertical_gap/target_value',
        source='TBL-Sl2:MC-Zg-01:Mtr.VAL',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/small_slit_2_vertical_gap/value': F144Stream(
        nexus_path='/entry/instrument/small_slit_2_vertical_gap/value',
        source='TBL-Sl2:MC-Zg-01:Mtr.RBV',
        topic='tbl_motion',
        units='mm',
    ),
    '/entry/instrument/source/beam_cycle_id': F144Stream(
        nexus_path='/entry/instrument/source/beam_cycle_id',
        source='TD-M:Ctrl-EVR-1:DbufCycleId-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_destination': F144Stream(
        nexus_path='/entry/instrument/source/beam_destination',
        source='TD-M:Ctrl-EVR-1:DbufBDest-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_destination_mode': F144Stream(
        nexus_path='/entry/instrument/source/beam_destination_mode',
        source='TD-M:Ctrl-EVR-1:DbufBDest-II',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_present': F144Stream(
        nexus_path='/entry/instrument/source/beam_present',
        source='TD-M:Ctrl-EVR-1:DbufBPresent-II',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_pulse_end_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/beam_pulse_end_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtBPulseEndCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_pulse_end_event_id': F144Stream(
        nexus_path='/entry/instrument/source/beam_pulse_end_event_id',
        source='TD-M:Ctrl-EVR-1:EvtBPulseEndId-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_pulse_start_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/beam_pulse_start_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtBPulseStCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beam_state': F144Stream(
        nexus_path='/entry/instrument/source/beam_state',
        source='TD-M:Ctrl-EVR-1:DbufBState-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/beamdump_pulse_charge_010': F144Stream(
        nexus_path='/entry/instrument/source/beamdump_pulse_charge_010',
        source='DmpL-010Drf:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/source/beamdump_pulse_charge_040': F144Stream(
        nexus_path='/entry/instrument/source/beamdump_pulse_charge_040',
        source='DmpL-040Drf:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/source/bunch_length': F144Stream(
        nexus_path='/entry/instrument/source/bunch_length',
        source='TD-M:Ctrl-EVR-1:DbufBLen-I',
        topic='tn_data_general',
        units='us',
    ),
    '/entry/instrument/source/bunch_pattern': F144Stream(
        nexus_path='/entry/instrument/source/bunch_pattern',
        source='TD-M:Ctrl-EVR-1:DbufTgRast-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/cryo_tt_82025_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82025_temperature',
        source='CrS-CMS:Cryo-TT-82025:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/cryo_tt_82027_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82027_temperature',
        source='CrS-CMS:Cryo-TT-82027:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/cryo_tt_82029_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82029_temperature',
        source='CrS-CMS:Cryo-TT-82029:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/cryo_tt_82031_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82031_temperature',
        source='CrS-CMS:Cryo-TT-82031:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/cryo_tt_82033_temperature': F144Stream(
        nexus_path='/entry/instrument/source/cryo_tt_82033_temperature',
        source='CrS-CMS:Cryo-TT-82033:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/source/current': F144Stream(
        nexus_path='/entry/instrument/source/current',
        source='TD-M:Ctrl-EVR-1:DbufBCurr-I',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/instrument/source/cycle_start_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/cycle_start_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtF14HzCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/data_buffer_sent_offset': F144Stream(
        nexus_path='/entry/instrument/source/data_buffer_sent_offset',
        source='TD-M:Ctrl-SCE-1:DbufSentOffset-SP',
        topic='tn_data_general',
        units='us',
    ),
    '/entry/instrument/source/energy': F144Stream(
        nexus_path='/entry/instrument/source/energy',
        source='TD-M:Ctrl-EVR-1:DbufBEn-I',
        topic='tn_data_general',
        units='keV',
    ),
    '/entry/instrument/source/flat_top_current': F144Stream(
        nexus_path='/entry/instrument/source/flat_top_current',
        source='A2T-130LWU:PBI-BCM-001:FlatTopCurrentR',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/instrument/source/fsm_machine_active': F144Stream(
        nexus_path='/entry/instrument/source/fsm_machine_active',
        source='CrS-CMS:SC-FSM-007x:STS_Active',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/high_beta_flat_top_current': F144Stream(
        nexus_path='/entry/instrument/source/high_beta_flat_top_current',
        source='HEBT-160LWU:PBI-BCM-001:FlatTopCurrentR',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/instrument/source/high_beta_pulse_charge': F144Stream(
        nexus_path='/entry/instrument/source/high_beta_pulse_charge',
        source='HEBT-160LWU:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/source/high_beta_pulse_width': F144Stream(
        nexus_path='/entry/instrument/source/high_beta_pulse_width',
        source='HEBT-160LWU:PBI-BCM-001:PulseWidthR',
        topic='tn_data_general',
        units='us',
    ),
    '/entry/instrument/source/mode': F144Stream(
        nexus_path='/entry/instrument/source/mode',
        source='TD-M:Ctrl-EVR-1:DbufBMod-II',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/ni_acq_start_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/ni_acq_start_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtNiAcqStCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/ni_sync_event_counter': F144Stream(
        nexus_path='/entry/instrument/source/ni_sync_event_counter',
        source='TD-M:Ctrl-EVR-1:EvtNiSyncCnt-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/source/pulse_charge': F144Stream(
        nexus_path='/entry/instrument/source/pulse_charge',
        source='A2T-130LWU:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/source/pulse_width': F144Stream(
        nexus_path='/entry/instrument/source/pulse_width',
        source='A2T-130LWU:PBI-BCM-001:PulseWidthR',
        topic='tn_data_general',
        units='us',
    ),
    '/entry/instrument/source/target_segment': F144Stream(
        nexus_path='/entry/instrument/source/target_segment',
        source='TD-M:Ctrl-EVR-1:DbufTgSeg-I',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/tilt_1/idle_flag': F144Stream(
        nexus_path='/entry/instrument/tilt_1/idle_flag',
        source='TBL-TBL:MC-Pos-309:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/tilt_1/target_value': F144Stream(
        nexus_path='/entry/instrument/tilt_1/target_value',
        source='TBL-TBL:MC-Pos-309:Mtr.VAL',
        topic='tbl_motion',
        units='degrees',
    ),
    '/entry/instrument/tilt_1/value': F144Stream(
        nexus_path='/entry/instrument/tilt_1/value',
        source='TBL-TBL:MC-Pos-309:Mtr.RBV',
        topic='tbl_motion',
        units='degrees',
    ),
    '/entry/instrument/tilt_2/idle_flag': F144Stream(
        nexus_path='/entry/instrument/tilt_2/idle_flag',
        source='TBL-TBL:MC-Pos-310:Mtr.DMOV',
        topic='tbl_motion',
        units='dimensionless',
    ),
    '/entry/instrument/tilt_2/target_value': F144Stream(
        nexus_path='/entry/instrument/tilt_2/target_value',
        source='TBL-TBL:MC-Pos-310:Mtr.VAL',
        topic='tbl_motion',
        units='degrees',
    ),
    '/entry/instrument/tilt_2/value': F144Stream(
        nexus_path='/entry/instrument/tilt_2/value',
        source='TBL-TBL:MC-Pos-310:Mtr.RBV',
        topic='tbl_motion',
        units='degrees',
    ),
    '/entry/instrument/timepix3_detector/intensifier': F144Stream(
        nexus_path='/entry/instrument/timepix3_detector/intensifier',
        source='TBL-DtTPX:NDet-ImgInt-001:AO0',
        topic='tbl_misc_devices',
        units='V',
    ),
}
