# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Scipp contributors (https://github.com/scipp)
"""Auto-generated NeXus f144 stream declarations.

Do not edit by hand. Regenerate with
``python -m ess.livedata.nexus_helpers <geometry.nxs> --generate``.

Source: coda_magic_999999_00015510.hdf
"""

from ess.livedata.config import F144Stream

PARSED_STREAMS: dict[str, F144Stream] = {
    '/entry/instrument/bandwidth_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/bandwidth_chopper/delay',
        source='MAGIC-ChpSy1:Chop-BC-201:TotDly',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/bandwidth_chopper/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/bandwidth_chopper/experiment_delay',
        source='MAGIC-ChpSy1:Chop-BC-201:ChopDly-S',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/bandwidth_chopper/mechanical_delay': F144Stream(
        nexus_path='/entry/instrument/bandwidth_chopper/mechanical_delay',
        source='MAGIC-ChpSy1:Chop-BC-201:MechDly-S',
        topic='magic_choppers',
        units='degrees',
    ),
    '/entry/instrument/bandwidth_chopper/park_angle': F144Stream(
        nexus_path='/entry/instrument/bandwidth_chopper/park_angle',
        source='MAGIC-ChpSy1:Chop-BC-201:Pos_R',
        topic='magic_choppers',
        units='degrees',
    ),
    '/entry/instrument/bandwidth_chopper/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/bandwidth_chopper/pulse_delay',
        source='MAGIC-ChpSy1:Chop-BC-201:BeamPosDly-S',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/bandwidth_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/bandwidth_chopper/rotation_speed',
        source='MAGIC-ChpSy1:Chop-BC-201:Spd_R',
        topic='magic_choppers',
        units='Hz',
    ),
    '/entry/instrument/bandwidth_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/bandwidth_chopper/rotation_speed_setpoint',
        source='MAGIC-ChpSy1:Chop-BC-201:Spd_S',
        topic='magic_choppers',
        units='Hz',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_bottom/idle_flag',
        source='MAGIC-ColSl1:MC-SlZm-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_bottom/target_value',
        source='MAGIC-ColSl1:MC-SlZm-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_bottom/value',
        source='MAGIC-ColSl1:MC-SlZm-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_left/idle_flag',
        source='MAGIC-ColSl1:MC-SlYp-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_left/target_value',
        source='MAGIC-ColSl1:MC-SlYp-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_left/value',
        source='MAGIC-ColSl1:MC-SlYp-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_right/idle_flag',
        source='MAGIC-ColSl1:MC-SlYm-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_right/target_value',
        source='MAGIC-ColSl1:MC-SlYm-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_right/value',
        source='MAGIC-ColSl1:MC-SlYm-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_top/idle_flag',
        source='MAGIC-ColSl1:MC-SlZp-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_top/target_value',
        source='MAGIC-ColSl1:MC-SlZp-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_1/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_1/blade_top/value',
        source='MAGIC-ColSl1:MC-SlZp-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_bottom/idle_flag',
        source='TODO-MAGIC-ColSl1:MC-SlZm-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_bottom/target_value',
        source='TODO-MAGIC-ColSl1:MC-SlZm-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_bottom/value',
        source='TODO-MAGIC-ColSl1:MC-SlZm-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_left/idle_flag',
        source='TODO-MAGIC-ColSl1:MC-SlYp-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_left/target_value',
        source='TODO-MAGIC-ColSl1:MC-SlYp-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_left/value',
        source='TODO-MAGIC-ColSl1:MC-SlYp-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_right/idle_flag',
        source='TODO-MAGIC-ColSl1:MC-SlYm-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_right/target_value',
        source='TODO-MAGIC-ColSl1:MC-SlYm-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_right/value',
        source='TODO-MAGIC-ColSl1:MC-SlYm-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_top/idle_flag',
        source='TODO-MAGIC-ColSl1:MC-SlZp-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_top/target_value',
        source='TODO-MAGIC-ColSl1:MC-SlZp-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_2/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_2/blade_top/value',
        source='TODO-MAGIC-ColSl1:MC-SlZp-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_bottom/idle_flag',
        source='MAGIC-ColSl3:MC-SlZm-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_bottom/target_value',
        source='MAGIC-ColSl3:MC-SlZm-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_bottom/value',
        source='MAGIC-ColSl3:MC-SlZm-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_left/idle_flag',
        source='MAGIC-ColSl3:MC-SlYp-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_left/target_value',
        source='MAGIC-ColSl3:MC-SlYp-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_left/value',
        source='MAGIC-ColSl3:MC-SlYp-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_right/idle_flag',
        source='MAGIC-ColSl3:MC-SlYm-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_right/target_value',
        source='MAGIC-ColSl3:MC-SlYm-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_right/value',
        source='MAGIC-ColSl3:MC-SlYm-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_top/idle_flag',
        source='MAGIC-ColSl3:MC-SlZp-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_top/target_value',
        source='MAGIC-ColSl3:MC-SlZp-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_3/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_3/blade_top/value',
        source='MAGIC-ColSl3:MC-SlZp-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_bottom/idle_flag',
        source='MAGIC-ColSl4:MC-SlZm-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_bottom/target_value',
        source='MAGIC-ColSl4:MC-SlZm-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_bottom/value',
        source='MAGIC-ColSl4:MC-SlZm-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_left/idle_flag',
        source='MAGIC-ColSl4:MC-SlYp-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_left/target_value',
        source='MAGIC-ColSl4:MC-SlYp-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_left/value',
        source='MAGIC-ColSl4:MC-SlYp-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_right/idle_flag',
        source='MAGIC-ColSl4:MC-SlYm-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_right/target_value',
        source='MAGIC-ColSl4:MC-SlYm-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_right/value',
        source='MAGIC-ColSl4:MC-SlYm-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_top/idle_flag',
        source='MAGIC-ColSl4:MC-SlZp-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_top/target_value',
        source='MAGIC-ColSl4:MC-SlZp-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimation_slit_set_4/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/collimation_slit_set_4/blade_top/value',
        source='MAGIC-ColSl4:MC-SlZp-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimator_oscillation/idle_flag': F144Stream(
        nexus_path='/entry/instrument/collimator_oscillation/idle_flag',
        source='placeholder.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/collimator_oscillation/target_value': F144Stream(
        nexus_path='/entry/instrument/collimator_oscillation/target_value',
        source='placeholder.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/collimator_oscillation/value': F144Stream(
        nexus_path='/entry/instrument/collimator_oscillation/value',
        source='placeholder.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/detector_a_rotation/idle_flag': F144Stream(
        nexus_path='/entry/instrument/detector_a_rotation/idle_flag',
        source='MAGIC-DtRot:MC-RotZ-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/detector_a_rotation/target_value': F144Stream(
        nexus_path='/entry/instrument/detector_a_rotation/target_value',
        source='MAGIC-DtRot:MC-RotZ-01.VAL',
        topic='magic_motion',
        units='degrees',
    ),
    '/entry/instrument/detector_a_rotation/value': F144Stream(
        nexus_path='/entry/instrument/detector_a_rotation/value',
        source='MAGIC-DtRot:MC-RotZ-01.RBV',
        topic='magic_motion',
        units='degrees',
    ),
    '/entry/instrument/detector_b_rotation/idle_flag': F144Stream(
        nexus_path='/entry/instrument/detector_b_rotation/idle_flag',
        source='MAGIC-DtRot:MC-RotZ-02.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/detector_b_rotation/target_value': F144Stream(
        nexus_path='/entry/instrument/detector_b_rotation/target_value',
        source='MAGIC-DtRot:MC-RotZ-02.VAL',
        topic='magic_motion',
        units='degrees',
    ),
    '/entry/instrument/detector_b_rotation/value': F144Stream(
        nexus_path='/entry/instrument/detector_b_rotation/value',
        source='MAGIC-DtRot:MC-RotZ-02.RBV',
        topic='magic_motion',
        units='degrees',
    ),
    '/entry/instrument/overlap_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/delay',
        source='MAGIC-ChpSy1:Chop-SC-101:TotDly',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/overlap_chopper/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/experiment_delay',
        source='MAGIC-ChpSy1:Chop-SC-101:ChopDly-S',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/overlap_chopper/mechanical_delay': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/mechanical_delay',
        source='MAGIC-ChpSy1:Chop-SC-101:MechDly-S',
        topic='magic_choppers',
        units='degrees',
    ),
    '/entry/instrument/overlap_chopper/park_angle': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/park_angle',
        source='MAGIC-ChpSy1:Chop-SC-101:Pos_R',
        topic='magic_choppers',
        units='degrees',
    ),
    '/entry/instrument/overlap_chopper/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/pulse_delay',
        source='MAGIC-ChpSy1:Chop-SC-101:BeamPosDly-S',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/overlap_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/rotation_speed',
        source='MAGIC-ChpSy1:Chop-SC-101:Spd_R',
        topic='magic_choppers',
        units='Hz',
    ),
    '/entry/instrument/overlap_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/overlap_chopper/rotation_speed_setpoint',
        source='MAGIC-ChpSy1:Chop-SC-101:Spd_S',
        topic='magic_choppers',
        units='Hz',
    ),
    '/entry/instrument/pulse_shape_chopper_1/delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_1/delay',
        source='MAGIC-ChpSy1:Chop-PSC-101:TotDly',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shape_chopper_1/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_1/experiment_delay',
        source='MAGIC-ChpSy1:Chop-PSC-101:ChopDly-S',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shape_chopper_1/mechanical_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_1/mechanical_delay',
        source='MAGIC-ChpSy1:Chop-PSC-101:MechDly-S',
        topic='magic_choppers',
        units='degrees',
    ),
    '/entry/instrument/pulse_shape_chopper_1/park_angle': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_1/park_angle',
        source='MAGIC-ChpSy1:Chop-PSC-101:Pos_R',
        topic='magic_choppers',
        units='degrees',
    ),
    '/entry/instrument/pulse_shape_chopper_1/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_1/pulse_delay',
        source='MAGIC-ChpSy1:Chop-PSC-101:BeamPosDly-S',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shape_chopper_1/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_1/rotation_speed',
        source='MAGIC-ChpSy1:Chop-PSC-101:Spd_R',
        topic='magic_choppers',
        units='Hz',
    ),
    '/entry/instrument/pulse_shape_chopper_1/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_1/rotation_speed_setpoint',
        source='MAGIC-ChpSy1:Chop-PSC-101:Spd_S',
        topic='magic_choppers',
        units='Hz',
    ),
    '/entry/instrument/pulse_shape_chopper_2/delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_2/delay',
        source='MAGIC-ChpSy1:Chop-PSC-102:TotDly',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shape_chopper_2/experiment_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_2/experiment_delay',
        source='MAGIC-ChpSy1:Chop-PSC-102:ChopDly-S',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shape_chopper_2/mechanical_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_2/mechanical_delay',
        source='MAGIC-ChpSy1:Chop-PSC-102:MechDly-S',
        topic='magic_choppers',
        units='degrees',
    ),
    '/entry/instrument/pulse_shape_chopper_2/park_angle': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_2/park_angle',
        source='MAGIC-ChpSy1:Chop-PSC-102:Pos_R',
        topic='magic_choppers',
        units='degrees',
    ),
    '/entry/instrument/pulse_shape_chopper_2/pulse_delay': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_2/pulse_delay',
        source='MAGIC-ChpSy1:Chop-PSC-102:BeamPosDly-S',
        topic='magic_choppers',
        units='ns',
    ),
    '/entry/instrument/pulse_shape_chopper_2/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_2/rotation_speed',
        source='MAGIC-ChpSy1:Chop-PSC-102:Spd_R',
        topic='magic_choppers',
        units='Hz',
    ),
    '/entry/instrument/pulse_shape_chopper_2/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/pulse_shape_chopper_2/rotation_speed_setpoint',
        source='MAGIC-ChpSy1:Chop-PSC-102:Spd_S',
        topic='magic_choppers',
        units='Hz',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_1/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_1/idle_flag',
        source='MAGIC-SpAnc1:MC-LinX-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_1/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_1/target_value',
        source='MAGIC-SpAnc1:MC-LinX-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_1/value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_1/value',
        source='MAGIC-SpAnc1:MC-LinX-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_2/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_2/idle_flag',
        source='MAGIC-SpAnc2:MC-LinX-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_2/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_2/target_value',
        source='MAGIC-SpAnc2:MC-LinX-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_2/value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_2/value',
        source='MAGIC-SpAnc2:MC-LinX-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_3/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_3/idle_flag',
        source='MAGIC-SpAnc3:MC-LinX-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_3/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_3/target_value',
        source='MAGIC-SpAnc3:MC-LinX-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_3/value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_3/value',
        source='MAGIC-SpAnc3:MC-LinX-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_4/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_4/idle_flag',
        source='MAGIC-SpAnc4:MC-LinX-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_4/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_4/target_value',
        source='MAGIC-SpAnc4:MC-LinX-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_4/value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_4/value',
        source='MAGIC-SpAnc4:MC-LinX-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_5/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_5/idle_flag',
        source='MAGIC-SpAnc5:MC-LinX-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_5/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_5/target_value',
        source='MAGIC-SpAnc5:MC-LinX-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_5/value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_5/value',
        source='MAGIC-SpAnc5:MC-LinX-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_6/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_6/idle_flag',
        source='MAGIC-SpAnc6:MC-LinX-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_6/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_6/target_value',
        source='MAGIC-SpAnc6:MC-LinX-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_area_ancilliary_axis_6/value': F144Stream(
        nexus_path='/entry/instrument/sample_area_ancilliary_axis_6/value',
        source='MAGIC-SpAnc6:MC-LinX-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_1/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_1/idle_flag',
        source='MAGIC-SpEnv3:MC-Lin-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_1/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_1/target_value',
        source='MAGIC-SpEnv3:MC-Lin-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_1/value': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_1/value',
        source='MAGIC-SpEnv3:MC-Lin-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_2/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_2/idle_flag',
        source='MAGIC-SpEnv4:MC-Lin-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_2/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_2/target_value',
        source='MAGIC-SpEnv4:MC-Lin-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_2/value': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_2/value',
        source='MAGIC-SpEnv4:MC-Lin-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_3/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_3/idle_flag',
        source='TODO-MAGIC-SpEnv3:MC-Lin-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_3/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_3/target_value',
        source='TODO-MAGIC-SpEnv3:MC-Lin-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_3/value': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_3/value',
        source='TODO-MAGIC-SpEnv3:MC-Lin-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_4/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_4/idle_flag',
        source='TODO-MAGIC-SpEnv4:MC-Lin-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_4/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_4/target_value',
        source='TODO-MAGIC-SpEnv4:MC-Lin-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_environemnt_ancilliary_axis_4/value': F144Stream(
        nexus_path='/entry/instrument/sample_environemnt_ancilliary_axis_4/value',
        source='TODO-MAGIC-SpEnv4:MC-Lin-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stick_lift/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stick_lift/idle_flag',
        source='MAGIC-SpEnv2:MC-LinZ-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stick_lift/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stick_lift/target_value',
        source='MAGIC-SpEnv2:MC-LinZ-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stick_lift/value': F144Stream(
        nexus_path='/entry/instrument/sample_stick_lift/value',
        source='MAGIC-SpEnv2:MC-LinZ-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stick_rotation/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_stick_rotation/idle_flag',
        source='MAGIC-SpEnv1:MC-RotZ-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_stick_rotation/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_stick_rotation/target_value',
        source='MAGIC-SpEnv1:MC-RotZ-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_stick_rotation/value': F144Stream(
        nexus_path='/entry/instrument/sample_stick_rotation/value',
        source='MAGIC-SpEnv1:MC-RotZ-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_translation_x/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_translation_x/idle_flag',
        source='MAGIC-SpLin:MC-LinX-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_translation_x/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_translation_x/target_value',
        source='MAGIC-SpLin:MC-LinX-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_translation_x/value': F144Stream(
        nexus_path='/entry/instrument/sample_translation_x/value',
        source='MAGIC-SpLin:MC-LinX-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_translation_y/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_translation_y/idle_flag',
        source='MAGIC-SpLin:MC-LinY-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_translation_y/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_translation_y/target_value',
        source='MAGIC-SpLin:MC-LinY-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_translation_y/value': F144Stream(
        nexus_path='/entry/instrument/sample_translation_y/value',
        source='MAGIC-SpLin:MC-LinY-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_translation_z/idle_flag': F144Stream(
        nexus_path='/entry/instrument/sample_translation_z/idle_flag',
        source='MAGIC-SpLft:MC-LinZ-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/sample_translation_z/target_value': F144Stream(
        nexus_path='/entry/instrument/sample_translation_z/target_value',
        source='MAGIC-SpLft:MC-LinZ-01.VAL',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/sample_translation_z/value': F144Stream(
        nexus_path='/entry/instrument/sample_translation_z/value',
        source='MAGIC-SpLft:MC-LinZ-01.RBV',
        topic='magic_motion',
        units='mm',
    ),
    '/entry/instrument/solid_state_bender_rotation/idle_flag': F144Stream(
        nexus_path='/entry/instrument/solid_state_bender_rotation/idle_flag',
        source='MAGIC-SSBnd1:MC-RotX-01.DMOV',
        topic='magic_motion',
        units='dimensionless',
    ),
    '/entry/instrument/solid_state_bender_rotation/target_value': F144Stream(
        nexus_path='/entry/instrument/solid_state_bender_rotation/target_value',
        source='MAGIC-SSBnd1:MC-RotX-01.VAL',
        topic='magic_motion',
        units='degrees',
    ),
    '/entry/instrument/solid_state_bender_rotation/value': F144Stream(
        nexus_path='/entry/instrument/solid_state_bender_rotation/value',
        source='MAGIC-SSBnd1:MC-RotX-01.RBV',
        topic='magic_motion',
        units='degrees',
    ),
    '/entry/instrument/source/current': F144Stream(
        nexus_path='/entry/instrument/source/current',
        source='SIM_dream:instrument:source:current',
        topic='magic_nicos_devices',
        units='mA',
    ),
    '/entry/neutron_prod_info/cryo_tt_82025_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82025_temperature',
        source='CrS-CMS:Cryo-TT-82025:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82027_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82027_temperature',
        source='CrS-CMS:Cryo-TT-82027:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82029_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82029_temperature',
        source='CrS-CMS:Cryo-TT-82029:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82031_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82031_temperature',
        source='CrS-CMS:Cryo-TT-82031:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/cryo_tt_82033_temperature': F144Stream(
        nexus_path='/entry/neutron_prod_info/cryo_tt_82033_temperature',
        source='CrS-CMS:Cryo-TT-82033:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/neutron_prod_info/flat_top_current': F144Stream(
        nexus_path='/entry/neutron_prod_info/flat_top_current',
        source='A2T-130LWU:PBI-BCM-001:FlatTopCurrentR',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/neutron_prod_info/fsm_machine_active': F144Stream(
        nexus_path='/entry/neutron_prod_info/fsm_machine_active',
        source='CrS-CMS:SC-FSM-007x:STS_Active',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/neutron_prod_info/pulse_charge': F144Stream(
        nexus_path='/entry/neutron_prod_info/pulse_charge',
        source='A2T-130LWU:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/neutron_prod_info/pulse_width': F144Stream(
        nexus_path='/entry/neutron_prod_info/pulse_width',
        source='A2T-130LWU:PBI-BCM-001:PulseWidthR',
        topic='tn_data_general',
        units='ms',
    ),
}
