# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Scipp contributors (https://github.com/scipp)
"""Auto-generated NeXus f144 stream declarations.

Do not edit by hand. Regenerate with
``python -m ess.livedata.nexus_helpers <geometry.nxs> --generate``.

Source: coda_beer_999999_00015484.hdf
"""

from ess.livedata.config import F144Stream

PARSED_STREAMS: dict[str, F144Stream] = {
    '/entry/instrument/bi_spectral_switch/transformations/position_y': F144Stream(
        nexus_path='/entry/instrument/bi_spectral_switch/transformations/position_y',
        source='TODO48',
        topic='beer_motion',
        units='m',
    ),
    '/entry/instrument/bi_spectral_switch/value': F144Stream(
        nexus_path='/entry/instrument/bi_spectral_switch/value',
        source='TODO47',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/fc1a_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/fc1a_chopper/delay',
        source='TODO42',
        topic='beer_choppers',
        units='ns',
    ),
    '/entry/instrument/fc1a_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/fc1a_chopper/rotation_speed',
        source='TODO39',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/fc1a_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/fc1a_chopper/rotation_speed_setpoint',
        source='TODO40',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/fc2a_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/fc2a_chopper/delay',
        source='TODO46',
        topic='beer_choppers',
        units='ns',
    ),
    '/entry/instrument/fc2a_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/fc2a_chopper/rotation_speed',
        source='TODO43',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/fc2a_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/fc2a_chopper/rotation_speed_setpoint',
        source='TODO44',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/linear_collimator/value': F144Stream(
        nexus_path='/entry/instrument/linear_collimator/value',
        source='TODO51',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/mca_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/mca_chopper/delay',
        source='TODO38',
        topic='beer_choppers',
        units='ns',
    ),
    '/entry/instrument/mca_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/mca_chopper/rotation_speed',
        source='TODO35',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/mca_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/mca_chopper/rotation_speed_setpoint',
        source='TODO36',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82025_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82025_temperature',
        source='CrS-CMS:Cryo-TT-82025:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82027_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82027_temperature',
        source='CrS-CMS:Cryo-TT-82027:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82029_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82029_temperature',
        source='CrS-CMS:Cryo-TT-82029:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82031_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82031_temperature',
        source='CrS-CMS:Cryo-TT-82031:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/cryo_tt_82033_temperature': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/cryo_tt_82033_temperature',
        source='CrS-CMS:Cryo-TT-82033:MeasValue',
        topic='tn_data_general',
        units='K',
    ),
    '/entry/instrument/neutron_prod_info/flat_top_current': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/flat_top_current',
        source='A2T-130LWU:PBI-BCM-001:FlatTopCurrentR',
        topic='tn_data_general',
        units='mA',
    ),
    '/entry/instrument/neutron_prod_info/fsm_machine_active': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/fsm_machine_active',
        source='CrS-CMS:SC-FSM-007x:STS_Active',
        topic='tn_data_general',
        units='dimensionless',
    ),
    '/entry/instrument/neutron_prod_info/pulse_charge': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/pulse_charge',
        source='A2T-130LWU:PBI-BCM-001:PulseChargeR',
        topic='tn_data_general',
        units='uC',
    ),
    '/entry/instrument/neutron_prod_info/pulse_width': F144Stream(
        nexus_path='/entry/instrument/neutron_prod_info/pulse_width',
        source='A2T-130LWU:PBI-BCM-001:PulseWidthR',
        topic='tn_data_general',
        units='ms',
    ),
    '/entry/instrument/psc1_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/psc1_chopper/delay',
        source='TODO29',
        topic='beer_choppers',
        units='ns',
    ),
    '/entry/instrument/psc1_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/psc1_chopper/rotation_speed',
        source='TODO26',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/psc1_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/psc1_chopper/rotation_speed_setpoint',
        source='TODO27',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/psc2_chopper/delay': F144Stream(
        nexus_path='/entry/instrument/psc2_chopper/delay',
        source='TODO34',
        topic='beer_choppers',
        units='ns',
    ),
    '/entry/instrument/psc2_chopper/rotation_speed': F144Stream(
        nexus_path='/entry/instrument/psc2_chopper/rotation_speed',
        source='TODO31',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/psc2_chopper/rotation_speed_setpoint': F144Stream(
        nexus_path='/entry/instrument/psc2_chopper/rotation_speed_setpoint',
        source='TODO32',
        topic='beer_choppers',
        units='Hz',
    ),
    '/entry/instrument/psc2_chopper/transformations/position_z': F144Stream(
        nexus_path='/entry/instrument/psc2_chopper/transformations/position_z',
        source='TODO30',
        topic='beer_motion',
        units='m',
    ),
    '/entry/instrument/radial_collimator_1/value': F144Stream(
        nexus_path='/entry/instrument/radial_collimator_1/value',
        source='TODO49',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/radial_collimator_2/value': F144Stream(
        nexus_path='/entry/instrument/radial_collimator_2/value',
        source='TODO50',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_bottom/idle_flag',
        source='TODO12',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_bottom/target_value',
        source='TODO11',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_bottom/value',
        source='TODO10',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_left/idle_flag',
        source='TODO3',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_left/target_value',
        source='TODO2',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_left/value',
        source='TODO1',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_right/idle_flag',
        source='TODO6',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_right/target_value',
        source='TODO5',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_right/value',
        source='TODO4',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_top/idle_flag',
        source='TODO9',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_1/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_top/target_value',
        source='TODO8',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_1/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_1/blade_top/value',
        source='TODO7',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_bottom/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_bottom/idle_flag',
        source='TODO24',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_bottom/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_bottom/target_value',
        source='TODO23',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_bottom/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_bottom/value',
        source='TODO22',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_left/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_left/idle_flag',
        source='TODO15',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_left/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_left/target_value',
        source='TODO14',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_left/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_left/value',
        source='TODO13',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_right/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_right/idle_flag',
        source='TODO18',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_right/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_right/target_value',
        source='TODO17',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_right/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_right/value',
        source='TODO16',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_top/idle_flag': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_top/idle_flag',
        source='TODO21',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_2/blade_top/target_value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_top/target_value',
        source='TODO20',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_2/blade_top/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_2/blade_top/value',
        source='TODO19',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/value': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/value',
        source='TODO25',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/slit_set_3/x_gap': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/x_gap',
        source='beer_source_x',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/slit_set_3/y_gap': F144Stream(
        nexus_path='/entry/instrument/slit_set_3/y_gap',
        source='beer_source_y',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/symetrie_beer_hexapod/position_x/idle_flag': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/position_x/idle_flag',
        source='TODO54',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/symetrie_beer_hexapod/position_x/target_value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/position_x/target_value',
        source='TODO53',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/symetrie_beer_hexapod/position_x/value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/position_x/value',
        source='TODO52',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/symetrie_beer_hexapod/position_y/idle_flag': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/position_y/idle_flag',
        source='TODO57',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/symetrie_beer_hexapod/position_y/target_value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/position_y/target_value',
        source='TODO56',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/symetrie_beer_hexapod/position_y/value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/position_y/value',
        source='TODO55',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/symetrie_beer_hexapod/position_z/idle_flag': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/position_z/idle_flag',
        source='TODO60',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/symetrie_beer_hexapod/position_z/target_value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/position_z/target_value',
        source='TODO59',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/symetrie_beer_hexapod/position_z/value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/position_z/value',
        source='TODO58',
        topic='beer_motion',
        units='mm',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotary_stage/idle_flag': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotary_stage/idle_flag',
        source='TODO72',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotary_stage/target_value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotary_stage/target_value',
        source='TODO71',
        topic='beer_motion',
        units='degrees',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotary_stage/value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotary_stage/value',
        source='TODO70',
        topic='beer_motion',
        units='degrees',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotation_x/idle_flag': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotation_x/idle_flag',
        source='TODO63',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotation_x/target_value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotation_x/target_value',
        source='TODO62',
        topic='beer_motion',
        units='degrees',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotation_x/value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotation_x/value',
        source='TODO61',
        topic='beer_motion',
        units='degrees',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotation_y/idle_flag': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotation_y/idle_flag',
        source='TODO66',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotation_y/target_value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotation_y/target_value',
        source='TODO65',
        topic='beer_motion',
        units='degrees',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotation_y/value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotation_y/value',
        source='TODO64',
        topic='beer_motion',
        units='degrees',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotation_z/idle_flag': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotation_z/idle_flag',
        source='TODO69',
        topic='beer_motion',
        units='dimensionless',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotation_z/target_value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotation_z/target_value',
        source='TODO68',
        topic='beer_motion',
        units='degrees',
    ),
    '/entry/instrument/symetrie_beer_hexapod/rotation_z/value': F144Stream(
        nexus_path='/entry/instrument/symetrie_beer_hexapod/rotation_z/value',
        source='TODO67',
        topic='beer_motion',
        units='degrees',
    ),
}
